INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('France');
INSERT INTO Country(name) VALUES ('Sweden');
INSERT INTO Country(name) VALUES ('United States');
INSERT INTO Country(name) VALUES ('Palau');
INSERT INTO Country(name) VALUES ('Ukraine');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('Nigeria');
INSERT INTO Country(name) VALUES ('Indonesia');
INSERT INTO Country(name) VALUES ('Colombia');
INSERT INTO Country(name) VALUES ('Indonesia');
INSERT INTO Country(name) VALUES ('Armenia');
INSERT INTO Country(name) VALUES ('Mexico');
INSERT INTO Country(name) VALUES ('Czech Republic');
INSERT INTO Country(name) VALUES ('Jordan');
INSERT INTO Country(name) VALUES ('Uruguay');
INSERT INTO Country(name) VALUES ('Brazil');
INSERT INTO Country(name) VALUES ('Sudan');
INSERT INTO Country(name) VALUES ('Philippines');
INSERT INTO Country(name) VALUES ('Guatemala');
INSERT INTO Country(name) VALUES ('Indonesia');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('Israel');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('Indonesia');
INSERT INTO Country(name) VALUES ('Australia');
INSERT INTO Country(name) VALUES ('South Korea');
INSERT INTO Country(name) VALUES ('Mexico');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('Brazil');
INSERT INTO Country(name) VALUES ('Tanzania');
INSERT INTO Country(name) VALUES ('Indonesia');
INSERT INTO Country(name) VALUES ('Greece');
INSERT INTO Country(name) VALUES ('South Korea');
INSERT INTO Country(name) VALUES ('Iran');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('Malawi');
INSERT INTO Country(name) VALUES ('Poland');
INSERT INTO Country(name) VALUES ('Sweden');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('Canada');
INSERT INTO Country(name) VALUES ('Brazil');
INSERT INTO Country(name) VALUES ('Sri Lanka');
INSERT INTO Country(name) VALUES ('Guatemala');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('Indonesia');
INSERT INTO Country(name) VALUES ('Comoros');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('Colombia');
INSERT INTO Country(name) VALUES ('Uruguay');
INSERT INTO Country(name) VALUES ('France');
INSERT INTO Country(name) VALUES ('Bosnia and Herzegovina');
INSERT INTO Country(name) VALUES ('France');
INSERT INTO Country(name) VALUES ('Indonesia');
INSERT INTO Country(name) VALUES ('Philippines');
INSERT INTO Country(name) VALUES ('Russia');
INSERT INTO Country(name) VALUES ('Colombia');
INSERT INTO Country(name) VALUES ('Russia');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('Russia');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('Indonesia');
INSERT INTO Country(name) VALUES ('Thailand');
INSERT INTO Country(name) VALUES ('Russia');
INSERT INTO Country(name) VALUES ('Nigeria');
INSERT INTO Country(name) VALUES ('Indonesia');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('Czech Republic');
INSERT INTO Country(name) VALUES ('France');
INSERT INTO Country(name) VALUES ('United States');
INSERT INTO Country(name) VALUES ('Portugal');
INSERT INTO Country(name) VALUES ('Indonesia');
INSERT INTO Country(name) VALUES ('Palestinian Territory');
INSERT INTO Country(name) VALUES ('Canada');
INSERT INTO Country(name) VALUES ('Malaysia');
INSERT INTO Country(name) VALUES ('Poland');
INSERT INTO Country(name) VALUES ('Russia');
INSERT INTO Country(name) VALUES ('Nepal');
INSERT INTO Country(name) VALUES ('Sweden');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('Mexico');
INSERT INTO Country(name) VALUES ('Laos');
INSERT INTO Country(name) VALUES ('Indonesia');
INSERT INTO Country(name) VALUES ('France');
INSERT INTO Country(name) VALUES ('Ethiopia');
INSERT INTO Country(name) VALUES ('United States');
INSERT INTO Country(name) VALUES ('Serbia');
INSERT INTO Country(name) VALUES ('Yemen');
INSERT INTO Country(name) VALUES ('Brazil');
INSERT INTO Country(name) VALUES ('Cameroon');
INSERT INTO Country(name) VALUES ('Peru');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('Sweden');
INSERT INTO Country(name) VALUES ('Kazakhstan');
INSERT INTO Country(name) VALUES ('United States');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('Indonesia');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('Argentina');
INSERT INTO Country(name) VALUES ('Argentina');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('New Zealand');
INSERT INTO Country(name) VALUES ('Thailand');
INSERT INTO Country(name) VALUES ('Vietnam');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('Brazil');
INSERT INTO Country(name) VALUES ('Guatemala');
INSERT INTO Country(name) VALUES ('Somalia');
INSERT INTO Country(name) VALUES ('Philippines');
INSERT INTO Country(name) VALUES ('United States');
INSERT INTO Country(name) VALUES ('Indonesia');
INSERT INTO Country(name) VALUES ('Russia');
INSERT INTO Country(name) VALUES ('Indonesia');
INSERT INTO Country(name) VALUES ('Indonesia');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('Sweden');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('Saudi Arabia');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('Philippines');
INSERT INTO Country(name) VALUES ('Portugal');
INSERT INTO Country(name) VALUES ('France');
INSERT INTO Country(name) VALUES ('Peru');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('Brazil');
INSERT INTO Country(name) VALUES ('Mexico');
INSERT INTO Country(name) VALUES ('France');
INSERT INTO Country(name) VALUES ('El Salvador');
INSERT INTO Country(name) VALUES ('Thailand');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('Sweden');
INSERT INTO Country(name) VALUES ('Philippines');
INSERT INTO Country(name) VALUES ('Kenya');
INSERT INTO Country(name) VALUES ('Indonesia');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('Lithuania');
INSERT INTO Country(name) VALUES ('Russia');
INSERT INTO Country(name) VALUES ('Indonesia');
INSERT INTO Country(name) VALUES ('Thailand');
INSERT INTO Country(name) VALUES ('Poland');
INSERT INTO Country(name) VALUES ('Ukraine');
INSERT INTO Country(name) VALUES ('Philippines');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('Greece');
INSERT INTO Country(name) VALUES ('United States');
INSERT INTO Country(name) VALUES ('Chile');
INSERT INTO Country(name) VALUES ('Brazil');
INSERT INTO Country(name) VALUES ('Indonesia');
INSERT INTO Country(name) VALUES ('Indonesia');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('Portugal');
INSERT INTO Country(name) VALUES ('Russia');
INSERT INTO Country(name) VALUES ('Mexico');
INSERT INTO Country(name) VALUES ('United States');
INSERT INTO Country(name) VALUES ('Sweden');
INSERT INTO Country(name) VALUES ('Nigeria');
INSERT INTO Country(name) VALUES ('Indonesia');
INSERT INTO Country(name) VALUES ('Indonesia');
INSERT INTO Country(name) VALUES ('United States');
INSERT INTO Country(name) VALUES ('Philippines');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('Ethiopia');
INSERT INTO Country(name) VALUES ('Sweden');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('France');
INSERT INTO Country(name) VALUES ('Czech Republic');
INSERT INTO Country(name) VALUES ('Lebanon');
INSERT INTO Country(name) VALUES ('Ukraine');
INSERT INTO Country(name) VALUES ('Indonesia');
INSERT INTO Country(name) VALUES ('Brazil');
INSERT INTO Country(name) VALUES ('Indonesia');
INSERT INTO Country(name) VALUES ('Greece');
INSERT INTO Country(name) VALUES ('Philippines');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('China');
INSERT INTO Country(name) VALUES ('Kenya');
INSERT INTO Country(name) VALUES ('Russia');
INSERT INTO Country(name) VALUES ('Thailand');
INSERT INTO Country(name) VALUES ('Indonesia');
INSERT INTO Country(name) VALUES ('Brazil');
INSERT INTO Country(name) VALUES ('Palestinian Territory');
INSERT INTO Country(name) VALUES ('Indonesia');
INSERT INTO Country(name) VALUES ('Russia');
INSERT INTO Country(name) VALUES ('Indonesia');
INSERT INTO Country(name) VALUES ('Sweden');
INSERT INTO Country(name) VALUES ('Ukraine');
INSERT INTO Country(name) VALUES ('Peru');
INSERT INTO Country(name) VALUES ('Sweden');
INSERT INTO Country(name) VALUES ('Colombia');
INSERT INTO Country(name) VALUES ('Belarus');
INSERT INTO Country(name) VALUES ('Colombia');
INSERT INTO Country(name) VALUES ('Philippines');
INSERT INTO Country(name) VALUES ('Mongolia');
