INSERT INTO District(name) VALUES ('Évora');
INSERT INTO District(name) VALUES ('Évora');
INSERT INTO District(name) VALUES ('Akershus');
INSERT INTO District(name) VALUES ('Alaska');
INSERT INTO District(name) VALUES ('Alberta');
INSERT INTO District(name) VALUES ('Alberta');
INSERT INTO District(name) VALUES ('Alsace');
INSERT INTO District(name) VALUES ('Aquitaine');
INSERT INTO District(name) VALUES ('Aquitaine');
INSERT INTO District(name) VALUES ('Arizona');
INSERT INTO District(name) VALUES ('Arizona');
INSERT INTO District(name) VALUES ('Östergötland');
INSERT INTO District(name) VALUES ('Östergötland');
INSERT INTO District(name) VALUES ('Östergötland');
INSERT INTO District(name) VALUES ('Aust-Agder');
INSERT INTO District(name) VALUES ('Auvergne');
INSERT INTO District(name) VALUES ('Aveiro');
INSERT INTO District(name) VALUES ('Aveiro');
INSERT INTO District(name) VALUES ('Île-de-France');
INSERT INTO District(name) VALUES ('Île-de-France');
INSERT INTO District(name) VALUES ('Île-de-France');
INSERT INTO District(name) VALUES ('Île-de-France');
INSERT INTO District(name) VALUES ('Île-de-France');
INSERT INTO District(name) VALUES ('Braga');
INSERT INTO District(name) VALUES ('Braga');
INSERT INTO District(name) VALUES ('British Columbia');
INSERT INTO District(name) VALUES ('California');
INSERT INTO District(name) VALUES ('California');
INSERT INTO District(name) VALUES ('Cantabria');
INSERT INTO District(name) VALUES ('Castilla - Leon');
INSERT INTO District(name) VALUES ('Cataluna');
INSERT INTO District(name) VALUES ('Centre');
INSERT INTO District(name) VALUES ('Centre');
INSERT INTO District(name) VALUES ('Chiapas');
INSERT INTO District(name) VALUES ('Coimbra');
INSERT INTO District(name) VALUES ('Colorado');
INSERT INTO District(name) VALUES ('Dalarna');
INSERT INTO District(name) VALUES ('Dalarna');
INSERT INTO District(name) VALUES ('Dalarna');
INSERT INTO District(name) VALUES ('District of Columbia');
INSERT INTO District(name) VALUES ('Faro');
INSERT INTO District(name) VALUES ('Faro');
INSERT INTO District(name) VALUES ('Guarda');
INSERT INTO District(name) VALUES ('Guarda');
INSERT INTO District(name) VALUES ('Guerrero');
INSERT INTO District(name) VALUES ('Hajdú-Bihar');
INSERT INTO District(name) VALUES ('Halland');
INSERT INTO District(name) VALUES ('Hamburg');
INSERT INTO District(name) VALUES ('Hordaland');
INSERT INTO District(name) VALUES ('Hordaland');
INSERT INTO District(name) VALUES ('Ilha das Flores');
INSERT INTO District(name) VALUES ('Ilha de São Jorge');
INSERT INTO District(name) VALUES ('Ilha do Pico');
INSERT INTO District(name) VALUES ('Indiana');
INSERT INTO District(name) VALUES ('Indiana');
INSERT INTO District(name) VALUES ('Jämtland');
INSERT INTO District(name) VALUES ('Jönköping');
INSERT INTO District(name) VALUES ('Jalisco');
INSERT INTO District(name) VALUES ('Johor');
INSERT INTO District(name) VALUES ('Kalmar');
INSERT INTO District(name) VALUES ('Kuala Lumpur');
INSERT INTO District(name) VALUES ('Kuala Lumpur');
INSERT INTO District(name) VALUES ('Languedoc-Roussillon');
INSERT INTO District(name) VALUES ('Leiria');
INSERT INTO District(name) VALUES ('Leiria');
INSERT INTO District(name) VALUES ('Leiria');
INSERT INTO District(name) VALUES ('Leiria');
INSERT INTO District(name) VALUES ('Leiria');
INSERT INTO District(name) VALUES ('Lisboa');
INSERT INTO District(name) VALUES ('Lisboa');
INSERT INTO District(name) VALUES ('Lorraine');
INSERT INTO District(name) VALUES ('Louisiana');
INSERT INTO District(name) VALUES ('Manitoba');
INSERT INTO District(name) VALUES ('Maryland');
INSERT INTO District(name) VALUES ('Massachusetts');
INSERT INTO District(name) VALUES ('Michigan');
INSERT INTO District(name) VALUES ('Michigan');
INSERT INTO District(name) VALUES ('Midi-Pyrénées');
INSERT INTO District(name) VALUES ('Midi-Pyrénées');
INSERT INTO District(name) VALUES ('Minnesota');
INSERT INTO District(name) VALUES ('Murcia');
INSERT INTO District(name) VALUES ('Murcia');
INSERT INTO District(name) VALUES ('Nebraska');
INSERT INTO District(name) VALUES ('Nevada');
INSERT INTO District(name) VALUES ('New South Wales');
INSERT INTO District(name) VALUES ('New South Wales');
INSERT INTO District(name) VALUES ('New York');
INSERT INTO District(name) VALUES ('Norrbotten');
INSERT INTO District(name) VALUES ('Norrbotten');
INSERT INTO District(name) VALUES ('North Carolina');
INSERT INTO District(name) VALUES ('Nova Scotia');
INSERT INTO District(name) VALUES ('Ohio');
INSERT INTO District(name) VALUES ('Ohio');
INSERT INTO District(name) VALUES ('Ontario');
INSERT INTO District(name) VALUES ('Ontario');
INSERT INTO District(name) VALUES ('Pays de la Loire');
INSERT INTO District(name) VALUES ('Pays de la Loire');
INSERT INTO District(name) VALUES ('Pays de la Loire');
INSERT INTO District(name) VALUES ('Pennsylvania');
INSERT INTO District(name) VALUES ('Picardie');
INSERT INTO District(name) VALUES ('Poitou-Charentes');
INSERT INTO District(name) VALUES ('Poitou-Charentes');
INSERT INTO District(name) VALUES ('Poitou-Charentes');
INSERT INTO District(name) VALUES ('Portalegre');
INSERT INTO District(name) VALUES ('Porto');
INSERT INTO District(name) VALUES ('Porto');
INSERT INTO District(name) VALUES ('Porto');
INSERT INTO District(name) VALUES ('Provence-Alpes-Côte d''Azur');
INSERT INTO District(name) VALUES ('Provence-Alpes-Côte d''Azur');
INSERT INTO District(name) VALUES ('Provence-Alpes-Côte d''Azur');
INSERT INTO District(name) VALUES ('Provincie Drenthe');
INSERT INTO District(name) VALUES ('Provincie Flevoland');
INSERT INTO District(name) VALUES ('Provincie Noord-Brabant');
INSERT INTO District(name) VALUES ('Québec');
INSERT INTO District(name) VALUES ('Québec');
INSERT INTO District(name) VALUES ('Québec');
INSERT INTO District(name) VALUES ('Québec');
INSERT INTO District(name) VALUES ('Québec');
INSERT INTO District(name) VALUES ('Québec');
INSERT INTO District(name) VALUES ('Québec');
INSERT INTO District(name) VALUES ('Region Hovedstaden');
INSERT INTO District(name) VALUES ('Rhône-Alpes');
INSERT INTO District(name) VALUES ('Rhône-Alpes');
INSERT INTO District(name) VALUES ('Södermanland');
INSERT INTO District(name) VALUES ('Södermanland');
INSERT INTO District(name) VALUES ('Santarém');
INSERT INTO District(name) VALUES ('Santarém');
INSERT INTO District(name) VALUES ('Sarawak');
INSERT INTO District(name) VALUES ('Scotland');
INSERT INTO District(name) VALUES ('Setúbal');
INSERT INTO District(name) VALUES ('Setúbal');
INSERT INTO District(name) VALUES ('Skåne');
INSERT INTO District(name) VALUES ('Skåne');
INSERT INTO District(name) VALUES ('Steiermark');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Tamaulipas');
INSERT INTO District(name) VALUES ('Tamaulipas');
INSERT INTO District(name) VALUES ('Tamaulipas');
INSERT INTO District(name) VALUES ('Telemark');
INSERT INTO District(name) VALUES ('Telemark');
INSERT INTO District(name) VALUES ('Tennessee');
INSERT INTO District(name) VALUES ('Tennessee');
INSERT INTO District(name) VALUES ('Tennessee');
INSERT INTO District(name) VALUES ('Texas');
INSERT INTO District(name) VALUES ('Texas');
INSERT INTO District(name) VALUES ('Texas');
INSERT INTO District(name) VALUES ('Västernorrland');
INSERT INTO District(name) VALUES ('Västernorrland');
INSERT INTO District(name) VALUES ('Västra Götaland');
INSERT INTO District(name) VALUES ('Västra Götaland');
INSERT INTO District(name) VALUES ('Västra Götaland');
INSERT INTO District(name) VALUES ('Västra Götaland');
INSERT INTO District(name) VALUES ('Västra Götaland');
INSERT INTO District(name) VALUES ('Västra Götaland');
INSERT INTO District(name) VALUES ('Västra Götaland');
INSERT INTO District(name) VALUES ('Viana do Castelo');
INSERT INTO District(name) VALUES ('Virginia');
INSERT INTO District(name) VALUES ('Virginia');
INSERT INTO District(name) VALUES ('Viseu');
INSERT INTO District(name) VALUES ('Washington');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('New South Wales');
INSERT INTO District(name) VALUES ('Auvergne');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Arizona');
INSERT INTO District(name) VALUES ('Aquitaine');
INSERT INTO District(name) VALUES ('Nevada');
INSERT INTO District(name) VALUES ('Michigan');
INSERT INTO District(name) VALUES ('Iowa');
INSERT INTO District(name) VALUES ('Telemark');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Set�bal');
INSERT INTO District(name) VALUES ('Texas');
INSERT INTO District(name) VALUES ('Manitoba');
INSERT INTO District(name) VALUES ('Franche-Comt�');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Ontario');
INSERT INTO District(name) VALUES ('Qu�bec');
INSERT INTO District(name) VALUES ('Aquitaine');
INSERT INTO District(name) VALUES ('Arizona');
INSERT INTO District(name) VALUES ('England');
INSERT INTO District(name) VALUES ('Bragan�a');
INSERT INTO District(name) VALUES ('Ilha Terceira');
INSERT INTO District(name) VALUES ('Castilla - Leon');
INSERT INTO District(name) VALUES ('J�mtland');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('Region Hovedstaden');
INSERT INTO District(name) VALUES ('Bourgogne');
INSERT INTO District(name) VALUES ('Porto');
INSERT INTO District(name) VALUES ('Halland');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('Auvergne');
INSERT INTO District(name) VALUES ('V�stra G�taland');
INSERT INTO District(name) VALUES ('Viana do Castelo');
INSERT INTO District(name) VALUES ('Faro');
INSERT INTO District(name) VALUES ('Sk?ne');
INSERT INTO District(name) VALUES ('Kalmar');
INSERT INTO District(name) VALUES ('Santar�m');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Qu�bec');
INSERT INTO District(name) VALUES ('Provence-Alpes-C�te d''Azur');
INSERT INTO District(name) VALUES ('Ontario');
INSERT INTO District(name) VALUES ('Alberta');
INSERT INTO District(name) VALUES ('V�stra G�taland');
INSERT INTO District(name) VALUES ('Michigan');
INSERT INTO District(name) VALUES ('Viseu');
INSERT INTO District(name) VALUES ('Kalmar');
INSERT INTO District(name) VALUES ('Tennessee');
INSERT INTO District(name) VALUES ('Massachusetts');
INSERT INTO District(name) VALUES ('Alberta');
INSERT INTO District(name) VALUES ('Guerrero');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Nordland');
INSERT INTO District(name) VALUES ('Delaware');
INSERT INTO District(name) VALUES ('Virginia');
INSERT INTO District(name) VALUES ('Pays de la Loire');
INSERT INTO District(name) VALUES ('Sabah');
INSERT INTO District(name) VALUES ('Kuala Lumpur');
INSERT INTO District(name) VALUES ('Aveiro');
INSERT INTO District(name) VALUES ('Sk?ne');
INSERT INTO District(name) VALUES ('Bretagne');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Vaslui');
INSERT INTO District(name) VALUES ('Porto');
INSERT INTO District(name) VALUES ('Aust-Agder');
INSERT INTO District(name) VALUES ('Castilla - Leon');
INSERT INTO District(name) VALUES ('North Carolina');
INSERT INTO District(name) VALUES ('S�dermanland');
INSERT INTO District(name) VALUES ('Languedoc-Roussillon');
INSERT INTO District(name) VALUES ('Viseu');
INSERT INTO District(name) VALUES ('Viseu');
INSERT INTO District(name) VALUES ('Braga');
INSERT INTO District(name) VALUES ('V�sternorrland');
INSERT INTO District(name) VALUES ('Picardie');
INSERT INTO District(name) VALUES ('Ontario');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('Provence-Alpes-C�te d''Azur');
INSERT INTO District(name) VALUES ('Emilia-Romagna');
INSERT INTO District(name) VALUES ('Porto');
INSERT INTO District(name) VALUES ('Aust-Agder');
INSERT INTO District(name) VALUES ('V�stmanland');
INSERT INTO District(name) VALUES ('Louisiana');
INSERT INTO District(name) VALUES ('British Columbia');
INSERT INTO District(name) VALUES ('Campania');
INSERT INTO District(name) VALUES ('England');
INSERT INTO District(name) VALUES ('V�stmanland');
INSERT INTO District(name) VALUES ('Guerrero');
INSERT INTO District(name) VALUES ('Florida');
INSERT INTO District(name) VALUES ('Oklahoma');
INSERT INTO District(name) VALUES ('Viseu');
INSERT INTO District(name) VALUES ('California');
INSERT INTO District(name) VALUES ('Sk?ne');
INSERT INTO District(name) VALUES ('Oklahoma');
INSERT INTO District(name) VALUES ('Michigan');
INSERT INTO District(name) VALUES ('Coimbra');
INSERT INTO District(name) VALUES ('Berlin');
INSERT INTO District(name) VALUES ('California');
INSERT INTO District(name) VALUES ('New York');
INSERT INTO District(name) VALUES ('Sk?ne');
INSERT INTO District(name) VALUES ('Blekinge');
INSERT INTO District(name) VALUES ('Region Hovedstaden');
INSERT INTO District(name) VALUES ('Midi-Pyr�n�es');
INSERT INTO District(name) VALUES ('Bretagne');
INSERT INTO District(name) VALUES ('Castelo Branco');
INSERT INTO District(name) VALUES ('Veracruz Llave');
INSERT INTO District(name) VALUES ('Minnesota');
INSERT INTO District(name) VALUES ('Aquitaine');
INSERT INTO District(name) VALUES ('Western Australia');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Nordland');
INSERT INTO District(name) VALUES ('Niedersachsen');
INSERT INTO District(name) VALUES ('Texas');
INSERT INTO District(name) VALUES ('Nord-Pas-de-Calais');
INSERT INTO District(name) VALUES ('Ilha de S?o Miguel');
INSERT INTO District(name) VALUES ('Alsace');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('Coimbra');
INSERT INTO District(name) VALUES ('Aquitaine');
INSERT INTO District(name) VALUES ('V�stra G�taland');
INSERT INTO District(name) VALUES ('Durango');
INSERT INTO District(name) VALUES ('Set�bal');
INSERT INTO District(name) VALUES ('�vora');
INSERT INTO District(name) VALUES ('Sachsen-Anhalt');
INSERT INTO District(name) VALUES ('Poitou-Charentes');
INSERT INTO District(name) VALUES ('Guadeloupe');
INSERT INTO District(name) VALUES ('Virginia');
INSERT INTO District(name) VALUES ('Hidalgo');
INSERT INTO District(name) VALUES ('Centre');
INSERT INTO District(name) VALUES ('Mexico');
INSERT INTO District(name) VALUES ('V�stra G�taland');
INSERT INTO District(name) VALUES ('Friuli-Venezia Giulia');
INSERT INTO District(name) VALUES ('Set�bal');
INSERT INTO District(name) VALUES ('Provence-Alpes-C�te d''Azur');
INSERT INTO District(name) VALUES ('Florida');
INSERT INTO District(name) VALUES ('Provincie Drenthe');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Provence-Alpes-C�te d''Azur');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Oslo');
INSERT INTO District(name) VALUES ('Telemark');
INSERT INTO District(name) VALUES ('Faro');
INSERT INTO District(name) VALUES ('Mexico');
INSERT INTO District(name) VALUES ('Sk?ne');
INSERT INTO District(name) VALUES ('Hamburg');
INSERT INTO District(name) VALUES ('Nordrhein-Westfalen');
INSERT INTO District(name) VALUES ('Provincie Overijssel');
INSERT INTO District(name) VALUES ('Lisboa');
INSERT INTO District(name) VALUES ('Qu�bec');
INSERT INTO District(name) VALUES ('Hessen');
INSERT INTO District(name) VALUES ('Provincie Gelderland');
INSERT INTO District(name) VALUES ('Provincie Gelderland');
INSERT INTO District(name) VALUES ('Washington');
INSERT INTO District(name) VALUES ('ViseuManitoba');
INSERT INTO District(name) VALUES ('Johor');
INSERT INTO District(name) VALUES ('R�unionViseu�le-de-FranceMichigan');
INSERT INTO District(name) VALUES ('Nord-Pas-de-Calais');
INSERT INTO District(name) VALUES ('Dalarna');
INSERT INTO District(name) VALUES ('Qu�becViseuBraga');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('AquitaineProvence-Alpes-C�te d''Azur');
INSERT INTO District(name) VALUES ('BragaSelangor');
INSERT INTO District(name) VALUES ('Iowa');
INSERT INTO District(name) VALUES ('Blekinge');
INSERT INTO District(name) VALUES ('Alsace');
INSERT INTO District(name) VALUES ('Oaxaca');
INSERT INTO District(name) VALUES ('Ilha de S?o MiguelNorrbotten');
INSERT INTO District(name) VALUES ('Guerrero');
INSERT INTO District(name) VALUES ('DalarnaKuala Lumpur�le-de-France�le-de-France');
INSERT INTO District(name) VALUES ('V�stra G�taland');
INSERT INTO District(name) VALUES ('Santar�m');
INSERT INTO District(name) VALUES ('Set�balCorseCoahuila De Zaragoza');
INSERT INTO District(name) VALUES ('LisboaVila RealNordrhein-Westfalen');
INSERT INTO District(name) VALUES ('England');
INSERT INTO District(name) VALUES ('Lisboa');
INSERT INTO District(name) VALUES ('Rh�ne-Alpes�le-de-FranceViseuOslo');
INSERT INTO District(name) VALUES ('Poitou-CharentesManitoba');
INSERT INTO District(name) VALUES ('Newfoundland and Labrador');
INSERT INTO District(name) VALUES ('Louisiana');
INSERT INTO District(name) VALUES ('Ohio');
INSERT INTO District(name) VALUES ('New JerseyWallonieLeiriaBourgogne');
INSERT INTO District(name) VALUES ('ViseuChihuahua');
INSERT INTO District(name) VALUES ('California');
INSERT INTO District(name) VALUES ('ArizonaCaliforniaNew YorkIlha de S?o Miguel');
INSERT INTO District(name) VALUES ('South Carolina');
INSERT INTO District(name) VALUES ('Leiria');
INSERT INTO District(name) VALUES ('Provincie Zuid-HollandJ�mtland');
INSERT INTO District(name) VALUES ('Wallonie');
INSERT INTO District(name) VALUES ('GeorgiaJ�nk�pingArizonaFranche-Comt�');
INSERT INTO District(name) VALUES ('Murcia');
INSERT INTO District(name) VALUES ('Santar�m');
INSERT INTO District(name) VALUES ('Nord-Pas-de-CalaisSk?ne');
INSERT INTO District(name) VALUES ('�le-de-FranceLimousinIlha de S?o Jorge');
INSERT INTO District(name) VALUES ('Florida');
INSERT INTO District(name) VALUES ('Kuala Lumpur');
INSERT INTO District(name) VALUES ('Putrajaya');
INSERT INTO District(name) VALUES ('BragaAlbertaHallandStockholmNordrhein-Westfalen');
INSERT INTO District(name) VALUES ('AveiroColorado');
INSERT INTO District(name) VALUES ('�le-de-FranceKedah');
INSERT INTO District(name) VALUES ('BerlinHaute-NormandieLeiria');
INSERT INTO District(name) VALUES ('FloridaTexas');
INSERT INTO District(name) VALUES ('Porto');
INSERT INTO District(name) VALUES ('Tabasco');
INSERT INTO District(name) VALUES ('Emilia-Romagna');
INSERT INTO District(name) VALUES ('V�sterbotten');
INSERT INTO District(name) VALUES ('Kuala Lumpur�le-de-FranceKelantan');
INSERT INTO District(name) VALUES ('British ColumbiaBraga');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Alberta');
INSERT INTO District(name) VALUES ('Ilha do PicoBretagne');
INSERT INTO District(name) VALUES ('�le-de-FranceTamaulipas');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('Jalisco');
INSERT INTO District(name) VALUES ('Massachusetts');
INSERT INTO District(name) VALUES ('V�stra G�taland');
INSERT INTO District(name) VALUES ('Veracruz LlaveRegion Hovedstaden');
INSERT INTO District(name) VALUES ('ChiapasDistrict of ColumbiaNebraska');
INSERT INTO District(name) VALUES ('Porto');
INSERT INTO District(name) VALUES ('California');
INSERT INTO District(name) VALUES ('Pays de la Loire');
INSERT INTO District(name) VALUES ('BudapestBaden-W�rttembergProvence-Alpes-C�te d''Azur�le-de-France');
INSERT INTO District(name) VALUES ('HallandGuanajuato');
INSERT INTO District(name) VALUES ('KronobergR�unionGuerreroOregonOslo');
INSERT INTO District(name) VALUES ('J�nk�ping');
INSERT INTO District(name) VALUES ('StockholmV�stra G�talandV�stra G�talandKentuckySantar�m�le-de-FranceNorthern IrelandV�stra G�talandChiapas');
INSERT INTO District(name) VALUES ('NorrbottenKelantan');
INSERT INTO District(name) VALUES ('Provincie Zuid-HollandVeneto');
INSERT INTO District(name) VALUES ('Mexico�le-de-FranceProvincie Limburg');
INSERT INTO District(name) VALUES ('Oaxaca');
INSERT INTO District(name) VALUES ('ArizonaOsloLisboa');
INSERT INTO District(name) VALUES ('ViseuOhioBraga');
INSERT INTO District(name) VALUES ('HidalgoSantar�m');
INSERT INTO District(name) VALUES ('Aveiro');
INSERT INTO District(name) VALUES ('Qu�becIlha da MadeiraJ�nk�ping');
INSERT INTO District(name) VALUES ('J�nk�ping');
INSERT INTO District(name) VALUES ('Franche-Comt�AlsaceStockholmRh�ne-Alpes');
INSERT INTO District(name) VALUES ('Leiria');
INSERT INTO District(name) VALUES ('Hamburg');
INSERT INTO District(name) VALUES ('Bourgogne');
INSERT INTO District(name) VALUES ('Illinois');
INSERT INTO District(name) VALUES ('Porto');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('Alberta');
INSERT INTO District(name) VALUES ('Texas');
INSERT INTO District(name) VALUES ('Baleares');
INSERT INTO District(name) VALUES ('Set�bal');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('Dalarna');
INSERT INTO District(name) VALUES ('California');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Aquitaine');
INSERT INTO District(name) VALUES ('Coimbra');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Qu�bec');
INSERT INTO District(name) VALUES ('Nova Scotia');
INSERT INTO District(name) VALUES ('Norrbotten');
INSERT INTO District(name) VALUES ('Braga');
INSERT INTO District(name) VALUES ('�sterg�tland');
INSERT INTO District(name) VALUES ('Guadeloupe');
INSERT INTO District(name) VALUES ('Tennessee');
INSERT INTO District(name) VALUES ('Viana do Castelo');
INSERT INTO District(name) VALUES ('Washington');
INSERT INTO District(name) VALUES ('Pulau Pinang');
INSERT INTO District(name) VALUES ('Basse-Normandie');
INSERT INTO District(name) VALUES ('Arkansas');
INSERT INTO District(name) VALUES ('Coahuila De Zaragoza');
INSERT INTO District(name) VALUES ('Mexico');
INSERT INTO District(name) VALUES ('Castelo Branco');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Bretagne');
INSERT INTO District(name) VALUES ('Viana do Castelo');
INSERT INTO District(name) VALUES ('Ontario');
INSERT INTO District(name) VALUES ('Porto');
INSERT INTO District(name) VALUES ('Castelo Branco');
INSERT INTO District(name) VALUES ('S�dermanland');
INSERT INTO District(name) VALUES ('Martinique');
INSERT INTO District(name) VALUES ('Alberta');
INSERT INTO District(name) VALUES ('Chiapas');
INSERT INTO District(name) VALUES ('Hamburg');
INSERT INTO District(name) VALUES ('Hordaland');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('Lorraine');
INSERT INTO District(name) VALUES ('Porto');
INSERT INTO District(name) VALUES ('Viana do Castelo');
INSERT INTO District(name) VALUES ('V�stra G�taland');
INSERT INTO District(name) VALUES ('Oslo');
INSERT INTO District(name) VALUES ('Ostfold');
INSERT INTO District(name) VALUES ('Kuala Lumpur');
INSERT INTO District(name) VALUES ('England');
INSERT INTO District(name) VALUES ('British Columbia');
INSERT INTO District(name) VALUES ('Provincie Gelderland');
INSERT INTO District(name) VALUES ('Aquitaine');
INSERT INTO District(name) VALUES ('Picardie');
INSERT INTO District(name) VALUES ('Nord-Pas-de-Calais');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('California');
INSERT INTO District(name) VALUES ('Hedmark');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Saskatchewan');
INSERT INTO District(name) VALUES ('Beja');
INSERT INTO District(name) VALUES ('British Columbia');
INSERT INTO District(name) VALUES ('Texas');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Auvergne');
INSERT INTO District(name) VALUES ('Michigan');
INSERT INTO District(name) VALUES ('Illinois');
INSERT INTO District(name) VALUES ('Ohio');
INSERT INTO District(name) VALUES ('Porto');
INSERT INTO District(name) VALUES ('Qu�bec');
INSERT INTO District(name) VALUES ('British Columbia');
INSERT INTO District(name) VALUES ('Rh�ne-Alpes');
INSERT INTO District(name) VALUES ('Region Hovedstaden');
INSERT INTO District(name) VALUES ('Ilha da Madeira');
INSERT INTO District(name) VALUES ('Poitou-Charentes');
INSERT INTO District(name) VALUES ('V�rmland');
INSERT INTO District(name) VALUES ('Leiria');
INSERT INTO District(name) VALUES ('British Columbia');
INSERT INTO District(name) VALUES ('Provincie Gelderland');
INSERT INTO District(name) VALUES ('Auvergne');
INSERT INTO District(name) VALUES ('Pays de la Loire');
INSERT INTO District(name) VALUES ('G�vleborg');
INSERT INTO District(name) VALUES ('Santar�m');
INSERT INTO District(name) VALUES ('Lisboa');
INSERT INTO District(name) VALUES ('Florida');
INSERT INTO District(name) VALUES ('Lisboa');
INSERT INTO District(name) VALUES ('Murcia');
INSERT INTO District(name) VALUES ('Newfoundland and Labrador');
INSERT INTO District(name) VALUES ('Centre');
INSERT INTO District(name) VALUES ('Santar�m');
INSERT INTO District(name) VALUES ('Tennessee');
INSERT INTO District(name) VALUES ('Region Hovedstaden');
INSERT INTO District(name) VALUES ('Alberta');
INSERT INTO District(name) VALUES ('Aquitaine');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('Braga');
INSERT INTO District(name) VALUES ('Provence-Alpes-C�te d''Azur');
INSERT INTO District(name) VALUES ('Ontario');
INSERT INTO District(name) VALUES ('Kelantan');
INSERT INTO District(name) VALUES ('�sterg�tland');
INSERT INTO District(name) VALUES ('Zala');
INSERT INTO District(name) VALUES ('Rh�ne-Alpes');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('Perak');
INSERT INTO District(name) VALUES ('England');
INSERT INTO District(name) VALUES ('Hordaland');
INSERT INTO District(name) VALUES ('Viseu');
INSERT INTO District(name) VALUES ('Picardie');
INSERT INTO District(name) VALUES ('England');
INSERT INTO District(name) VALUES ('Bragan�a');
INSERT INTO District(name) VALUES ('California');
INSERT INTO District(name) VALUES ('Utah');
INSERT INTO District(name) VALUES ('V�stra G�taland');
INSERT INTO District(name) VALUES ('England');
INSERT INTO District(name) VALUES ('Nordrhein-Westfalen');
INSERT INTO District(name) VALUES ('Halland');
INSERT INTO District(name) VALUES ('Pennsylvania');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('Budapest');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Uppsala');
INSERT INTO District(name) VALUES ('Braga');
INSERT INTO District(name) VALUES ('Beja');
INSERT INTO District(name) VALUES ('Lorraine');
INSERT INTO District(name) VALUES ('Rh�ne-Alpes');
INSERT INTO District(name) VALUES ('Guerrero');
INSERT INTO District(name) VALUES ('Manitoba');
INSERT INTO District(name) VALUES ('Poitou-Charentes');
INSERT INTO District(name) VALUES ('Sarawak');
INSERT INTO District(name) VALUES ('Georgia');
INSERT INTO District(name) VALUES ('Manitoba');
INSERT INTO District(name) VALUES ('Porto');
INSERT INTO District(name) VALUES ('Virginia');
INSERT INTO District(name) VALUES ('Alabama');
INSERT INTO District(name) VALUES ('Louisiana');
INSERT INTO District(name) VALUES ('Tamaulipas');
INSERT INTO District(name) VALUES ('Mexico');
INSERT INTO District(name) VALUES ('Arkansas');
INSERT INTO District(name) VALUES ('Guanajuato');
INSERT INTO District(name) VALUES ('Steiermark');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('Sk?ne');
INSERT INTO District(name) VALUES ('Lisboa');
INSERT INTO District(name) VALUES ('Provincie Overijssel');
INSERT INTO District(name) VALUES ('V�rmland');
INSERT INTO District(name) VALUES ('Kedah');
INSERT INTO District(name) VALUES ('Picardie');
INSERT INTO District(name) VALUES ('Pais Vasco');
INSERT INTO District(name) VALUES ('Connecticut');
INSERT INTO District(name) VALUES ('Manitoba');
INSERT INTO District(name) VALUES ('Mexico');
INSERT INTO District(name) VALUES ('V�sterbotten');
INSERT INTO District(name) VALUES ('Alberta');
INSERT INTO District(name) VALUES ('Faro');
INSERT INTO District(name) VALUES ('Vila Real');
INSERT INTO District(name) VALUES ('Ilha do Pico');
INSERT INTO District(name) VALUES ('Provincie Groningen');
INSERT INTO District(name) VALUES ('Tennessee');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('Lisboa');
INSERT INTO District(name) VALUES ('Coimbra');
INSERT INTO District(name) VALUES ('Pays de la Loire');
INSERT INTO District(name) VALUES ('Texas');
INSERT INTO District(name) VALUES ('Lombardia');
INSERT INTO District(name) VALUES ('Braga');
INSERT INTO District(name) VALUES ('Missouri');
INSERT INTO District(name) VALUES ('Berlin');
INSERT INTO District(name) VALUES ('Manitoba');
INSERT INTO District(name) VALUES ('Tennessee');
INSERT INTO District(name) VALUES ('Uppsala');
INSERT INTO District(name) VALUES ('Porto');
INSERT INTO District(name) VALUES ('Set�bal');
INSERT INTO District(name) VALUES ('Sonora');
INSERT INTO District(name) VALUES ('Basse-Normandie');
INSERT INTO District(name) VALUES ('England');
INSERT INTO District(name) VALUES ('Hessen');
INSERT INTO District(name) VALUES ('Sk?ne');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('South Carolina');
INSERT INTO District(name) VALUES ('Provence-Alpes-C�te d''Azur');
INSERT INTO District(name) VALUES ('Aveiro');
INSERT INTO District(name) VALUES ('New Jersey');
INSERT INTO District(name) VALUES ('Pennsylvania');
INSERT INTO District(name) VALUES ('Mississippi');
INSERT INTO District(name) VALUES ('Oslo');
INSERT INTO District(name) VALUES ('Virginia');
INSERT INTO District(name) VALUES ('Provincie Noord-Holland');
INSERT INTO District(name) VALUES ('Viseu');
INSERT INTO District(name) VALUES ('Centre');
INSERT INTO District(name) VALUES ('Braga');
INSERT INTO District(name) VALUES ('Sor-Trondelag');
INSERT INTO District(name) VALUES ('Ontario');
INSERT INTO District(name) VALUES ('Chiapas');
INSERT INTO District(name) VALUES ('Oslo');
INSERT INTO District(name) VALUES ('Set�bal');
INSERT INTO District(name) VALUES ('Aveiro');
INSERT INTO District(name) VALUES ('Virginia');
INSERT INTO District(name) VALUES ('Andalucia');
INSERT INTO District(name) VALUES ('Viana do Castelo');
INSERT INTO District(name) VALUES ('Qu�bec');
INSERT INTO District(name) VALUES ('Bretagne');
INSERT INTO District(name) VALUES ('Poitou-Charentes');
INSERT INTO District(name) VALUES ('Languedoc-Roussillon');
INSERT INTO District(name) VALUES ('North Carolina');
INSERT INTO District(name) VALUES ('Alsace');
INSERT INTO District(name) VALUES ('V�stra G�taland');
INSERT INTO District(name) VALUES ('Qu�bec');
INSERT INTO District(name) VALUES ('Berlin');
INSERT INTO District(name) VALUES ('Vestfold');
INSERT INTO District(name) VALUES ('V�stra G�taland');
INSERT INTO District(name) VALUES ('Nord-Pas-de-Calais');
INSERT INTO District(name) VALUES ('V�stra G�taland');
INSERT INTO District(name) VALUES ('Provincie Gelderland');
INSERT INTO District(name) VALUES ('Pays de la Loire');
INSERT INTO District(name) VALUES ('Uppsala');
INSERT INTO District(name) VALUES ('Viana do Castelo');
INSERT INTO District(name) VALUES ('Aveiro');
INSERT INTO District(name) VALUES ('�sterg�tland');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Braga');
INSERT INTO District(name) VALUES ('Veneto');
INSERT INTO District(name) VALUES ('Region Hovedstaden');
INSERT INTO District(name) VALUES ('Gujarat');
INSERT INTO District(name) VALUES ('Uppsala');
INSERT INTO District(name) VALUES ('Leiria');
INSERT INTO District(name) VALUES ('British Columbia');
INSERT INTO District(name) VALUES ('Rhode Island');
INSERT INTO District(name) VALUES ('Picardie');
INSERT INTO District(name) VALUES ('Nord-Pas-de-Calais');
INSERT INTO District(name) VALUES ('Florida');
INSERT INTO District(name) VALUES ('Poitou-Charentes');
INSERT INTO District(name) VALUES ('Sk?ne');
INSERT INTO District(name) VALUES ('Norrbotten');
INSERT INTO District(name) VALUES ('Lisboa');
INSERT INTO District(name) VALUES ('Nord-Pas-de-Calais');
INSERT INTO District(name) VALUES ('Norrbotten');
INSERT INTO District(name) VALUES ('Porto');
INSERT INTO District(name) VALUES ('North Carolina');
INSERT INTO District(name) VALUES ('Franche-Comt�');
INSERT INTO District(name) VALUES ('Veracruz Llave');
INSERT INTO District(name) VALUES ('Florida');
INSERT INTO District(name) VALUES ('Qu�bec');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('Hawaii');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Castelo Branco');
INSERT INTO District(name) VALUES ('California');
INSERT INTO District(name) VALUES ('Aveiro');
INSERT INTO District(name) VALUES ('Braga');
INSERT INTO District(name) VALUES ('California');
INSERT INTO District(name) VALUES ('G�vleborg');
INSERT INTO District(name) VALUES ('Louisiana');
INSERT INTO District(name) VALUES ('Berlin');
INSERT INTO District(name) VALUES ('Porto');
INSERT INTO District(name) VALUES ('Alsace');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Champagne-Ardenne');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('Ilha da Madeira');
INSERT INTO District(name) VALUES ('Kanton Luzern');
INSERT INTO District(name) VALUES ('Provincie Limburg');
INSERT INTO District(name) VALUES ('Braga');
INSERT INTO District(name) VALUES ('British Columbia');
INSERT INTO District(name) VALUES ('Baleares');
INSERT INTO District(name) VALUES ('Colorado');
INSERT INTO District(name) VALUES ('Nevada');
INSERT INTO District(name) VALUES ('British Columbia');
INSERT INTO District(name) VALUES ('Baranya');
INSERT INTO District(name) VALUES ('British Columbia');
INSERT INTO District(name) VALUES ('Sk?ne');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Ontario');
INSERT INTO District(name) VALUES ('Alberta');
INSERT INTO District(name) VALUES ('Region Hovedstaden');
INSERT INTO District(name) VALUES ('Provence-Alpes-C�te d''Azur');
INSERT INTO District(name) VALUES ('Nevada');
INSERT INTO District(name) VALUES ('Faro');
INSERT INTO District(name) VALUES ('Ontario');
INSERT INTO District(name) VALUES ('Louisiana');
INSERT INTO District(name) VALUES ('Provence-Alpes-C�te d''Azur');
INSERT INTO District(name) VALUES ('Chihuahua');
INSERT INTO District(name) VALUES ('Lorraine');
INSERT INTO District(name) VALUES ('Oaxaca');
INSERT INTO District(name) VALUES ('Putrajaya');
INSERT INTO District(name) VALUES ('Picardie');
INSERT INTO District(name) VALUES ('Aveiro');
INSERT INTO District(name) VALUES ('District of Columbia');
INSERT INTO District(name) VALUES ('Nevada');
INSERT INTO District(name) VALUES ('Qu�bec');
INSERT INTO District(name) VALUES ('Virginia');
INSERT INTO District(name) VALUES ('Tamaulipas');
INSERT INTO District(name) VALUES ('Alsace');
INSERT INTO District(name) VALUES ('Leiria');
INSERT INTO District(name) VALUES ('Porto');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Leiria');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('Pulau Pinang');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('Colorado');
INSERT INTO District(name) VALUES ('V�stra G�taland');
INSERT INTO District(name) VALUES ('B�k�s');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Oslo');
INSERT INTO District(name) VALUES ('New Mexico');
INSERT INTO District(name) VALUES ('Kalmar');
INSERT INTO District(name) VALUES ('Porto');
INSERT INTO District(name) VALUES ('Oklahoma');
INSERT INTO District(name) VALUES ('Haute-Normandie');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('�sterg�tland');
INSERT INTO District(name) VALUES ('Castelo Branco');
INSERT INTO District(name) VALUES ('Porto');
INSERT INTO District(name) VALUES ('Asturias');
INSERT INTO District(name) VALUES ('Texas');
INSERT INTO District(name) VALUES ('Texas');
INSERT INTO District(name) VALUES ('Porto');
INSERT INTO District(name) VALUES ('Castelo Branco');
INSERT INTO District(name) VALUES ('Porto');
INSERT INTO District(name) VALUES ('Rh�ne-Alpes');
INSERT INTO District(name) VALUES ('Rh�ne-Alpes');
INSERT INTO District(name) VALUES ('Nord-Pas-de-Calais');
INSERT INTO District(name) VALUES ('J�nk�ping');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('Puebla');
INSERT INTO District(name) VALUES ('Castelo Branco');
INSERT INTO District(name) VALUES ('�sterg�tland');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('Dalarna');
INSERT INTO District(name) VALUES ('Bretagne');
INSERT INTO District(name) VALUES ('Oaxaca');
INSERT INTO District(name) VALUES ('Georgia');
INSERT INTO District(name) VALUES ('Franche-Comt�');
INSERT INTO District(name) VALUES ('Lisboa');
INSERT INTO District(name) VALUES ('Nordrhein-Westfalen');
INSERT INTO District(name) VALUES ('J�nk�ping');
INSERT INTO District(name) VALUES ('Durango');
INSERT INTO District(name) VALUES ('Qu�bec');
INSERT INTO District(name) VALUES ('Qu�bec');
INSERT INTO District(name) VALUES ('Kuala Lumpur');
INSERT INTO District(name) VALUES ('Guadeloupe');
INSERT INTO District(name) VALUES ('Braga');
INSERT INTO District(name) VALUES ('Lombardia');
INSERT INTO District(name) VALUES ('Porto');
INSERT INTO District(name) VALUES ('Provincie Zuid-Holland');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('V�stra G�taland');
INSERT INTO District(name) VALUES ('Santar�m');
INSERT INTO District(name) VALUES ('Midi-Pyr�n�es');
INSERT INTO District(name) VALUES ('Florida');
INSERT INTO District(name) VALUES ('Guerrero');
INSERT INTO District(name) VALUES ('Jalisco');
INSERT INTO District(name) VALUES ('Texas');
INSERT INTO District(name) VALUES ('Ontario');
INSERT INTO District(name) VALUES ('Guerrero');
INSERT INTO District(name) VALUES ('Viseu');
INSERT INTO District(name) VALUES ('Coimbra');
INSERT INTO District(name) VALUES ('S�dermanland');
INSERT INTO District(name) VALUES ('Santar�m');
INSERT INTO District(name) VALUES ('Hordaland');
INSERT INTO District(name) VALUES ('Veracruz Llave');
INSERT INTO District(name) VALUES ('V�stra G�taland');
INSERT INTO District(name) VALUES ('Virginia');
INSERT INTO District(name) VALUES ('Poitou-Charentes');
INSERT INTO District(name) VALUES ('Provence-Alpes-C�te d''Azur');
INSERT INTO District(name) VALUES ('Rh�ne-Alpes');
INSERT INTO District(name) VALUES ('Provence-Alpes-C�te d''Azur');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('Poitou-Charentes');
INSERT INTO District(name) VALUES ('England');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Set�bal');
INSERT INTO District(name) VALUES ('Bourgogne');
INSERT INTO District(name) VALUES ('Sachsen');
INSERT INTO District(name) VALUES ('Provincie Noord-Holland');
INSERT INTO District(name) VALUES ('V�stra G�taland');
INSERT INTO District(name) VALUES ('�vora');
INSERT INTO District(name) VALUES ('Rh�ne-Alpes');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Leiria');
INSERT INTO District(name) VALUES ('San Luis Potosi');
INSERT INTO District(name) VALUES ('Beja');
INSERT INTO District(name) VALUES ('V�stra G�taland');
INSERT INTO District(name) VALUES ('Jalisco');
INSERT INTO District(name) VALUES ('Leiria');
INSERT INTO District(name) VALUES ('Tasmania');
INSERT INTO District(name) VALUES ('Region Hovedstaden');
INSERT INTO District(name) VALUES ('V�stra G�taland');
INSERT INTO District(name) VALUES ('Ilha da Madeira');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Sk?ne');
INSERT INTO District(name) VALUES ('Braga');
INSERT INTO District(name) VALUES ('British Columbia');
INSERT INTO District(name) VALUES ('V�stra G�taland');
INSERT INTO District(name) VALUES ('Braga');
INSERT INTO District(name) VALUES ('Sk?ne');
INSERT INTO District(name) VALUES ('V�stra G�taland');
INSERT INTO District(name) VALUES ('�sterg�tland');
INSERT INTO District(name) VALUES ('Viana do Castelo');
INSERT INTO District(name) VALUES ('Rh�ne-Alpes');
INSERT INTO District(name) VALUES ('Csongr�d');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Veracruz Llave');
INSERT INTO District(name) VALUES ('Veracruz Llave');
INSERT INTO District(name) VALUES ('Bretagne');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('Mexico');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Veracruz Llave');
INSERT INTO District(name) VALUES ('Florida');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('Newfoundland and Labrador');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Vila Real');
INSERT INTO District(name) VALUES ('Gy�r-Moson-Sopron');
INSERT INTO District(name) VALUES ('Kanton Graub�nden');
INSERT INTO District(name) VALUES ('Region Hovedstaden');
INSERT INTO District(name) VALUES ('Leiria');
INSERT INTO District(name) VALUES ('Lisboa');
INSERT INTO District(name) VALUES ('Saskatchewan');
INSERT INTO District(name) VALUES ('Braga');
INSERT INTO District(name) VALUES ('Guarda');
INSERT INTO District(name) VALUES ('V�stra G�taland');
INSERT INTO District(name) VALUES ('Oaxaca');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Indiana');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('�vora');
INSERT INTO District(name) VALUES ('Halland');
INSERT INTO District(name) VALUES ('Uppsala');
INSERT INTO District(name) VALUES ('Auvergne');
INSERT INTO District(name) VALUES ('R�union');
INSERT INTO District(name) VALUES ('R�union');
INSERT INTO District(name) VALUES ('Ontario');
INSERT INTO District(name) VALUES ('Viseu');
INSERT INTO District(name) VALUES ('Sk?ne');
INSERT INTO District(name) VALUES ('Rh�ne-Alpes');
INSERT INTO District(name) VALUES ('Set�bal');
INSERT INTO District(name) VALUES ('New South Wales');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('California');
INSERT INTO District(name) VALUES ('New South Wales');
INSERT INTO District(name) VALUES ('Veracruz Llave');
INSERT INTO District(name) VALUES ('California');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('New York');
INSERT INTO District(name) VALUES ('Oaxaca');
INSERT INTO District(name) VALUES ('Kedah');
INSERT INTO District(name) VALUES ('Porto');
INSERT INTO District(name) VALUES ('R�union');
INSERT INTO District(name) VALUES ('Selangor');
INSERT INTO District(name) VALUES ('Bretagne');
INSERT INTO District(name) VALUES ('Louisiana');
INSERT INTO District(name) VALUES ('Colorado');
INSERT INTO District(name) VALUES ('Alberta');
INSERT INTO District(name) VALUES ('Ontario');
INSERT INTO District(name) VALUES ('Provincie Limburg');
INSERT INTO District(name) VALUES ('Melaka');
INSERT INTO District(name) VALUES ('V�stra G�taland');
INSERT INTO District(name) VALUES ('Veracruz Llave');
INSERT INTO District(name) VALUES ('Alsace');
INSERT INTO District(name) VALUES ('�sterg�tland');
INSERT INTO District(name) VALUES ('California');
INSERT INTO District(name) VALUES ('Centre');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('Nord-Pas-de-Calais');
INSERT INTO District(name) VALUES ('Scotland');
INSERT INTO District(name) VALUES ('Braga');
INSERT INTO District(name) VALUES ('R�union');
INSERT INTO District(name) VALUES ('Set�bal');
INSERT INTO District(name) VALUES ('Midi-Pyr�n�es');
INSERT INTO District(name) VALUES ('Santar�m');
INSERT INTO District(name) VALUES ('California');
INSERT INTO District(name) VALUES ('Santar�m');
INSERT INTO District(name) VALUES ('�rebro');
INSERT INTO District(name) VALUES ('V�rmland');
INSERT INTO District(name) VALUES ('V�stra G�taland');
INSERT INTO District(name) VALUES ('Oaxaca');
INSERT INTO District(name) VALUES ('Guanajuato');
INSERT INTO District(name) VALUES ('Kuala Lumpur');
INSERT INTO District(name) VALUES ('Provincie Noord-Holland');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Hamburg');
INSERT INTO District(name) VALUES ('V�stra G�taland');
INSERT INTO District(name) VALUES ('Rh�ne-Alpes');
INSERT INTO District(name) VALUES ('Telemark');
INSERT INTO District(name) VALUES ('Liguria');
INSERT INTO District(name) VALUES ('Kuala Lumpur');
INSERT INTO District(name) VALUES ('Bruxelles-Capitale');
INSERT INTO District(name) VALUES ('Santar�m');
INSERT INTO District(name) VALUES ('Coimbra');
INSERT INTO District(name) VALUES ('Navarra');
INSERT INTO District(name) VALUES ('Sk?ne');
INSERT INTO District(name) VALUES ('Kanton Graub�nden');
INSERT INTO District(name) VALUES ('Viana do Castelo');
INSERT INTO District(name) VALUES ('Halland');
INSERT INTO District(name) VALUES ('J�nk�ping');
INSERT INTO District(name) VALUES ('Santar�m');
INSERT INTO District(name) VALUES ('Santar�m');
INSERT INTO District(name) VALUES ('North Carolina');
INSERT INTO District(name) VALUES ('Hessen');
INSERT INTO District(name) VALUES ('Rh�ne-Alpes');
INSERT INTO District(name) VALUES ('Nord-Pas-de-Calais');
INSERT INTO District(name) VALUES ('Manitoba');
INSERT INTO District(name) VALUES ('Ontario');
INSERT INTO District(name) VALUES ('Midi-Pyr�n�es');
INSERT INTO District(name) VALUES ('Chiapas');
INSERT INTO District(name) VALUES ('Braga');
INSERT INTO District(name) VALUES ('Mexico');
INSERT INTO District(name) VALUES ('Centre');
INSERT INTO District(name) VALUES ('Ontario');
INSERT INTO District(name) VALUES ('Bretagne');
INSERT INTO District(name) VALUES ('Kronoberg');
INSERT INTO District(name) VALUES ('Bretagne');
INSERT INTO District(name) VALUES ('Virginia');
INSERT INTO District(name) VALUES ('Kanton Bern');
INSERT INTO District(name) VALUES ('Jalisco');
INSERT INTO District(name) VALUES ('Hidalgo');
INSERT INTO District(name) VALUES ('Alsace');
INSERT INTO District(name) VALUES ('Lombardia');
INSERT INTO District(name) VALUES ('Porto');
INSERT INTO District(name) VALUES ('Halland');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('�sterg�tland');
INSERT INTO District(name) VALUES ('Aquitaine');
INSERT INTO District(name) VALUES ('New York');
INSERT INTO District(name) VALUES ('Oslo');
INSERT INTO District(name) VALUES ('Extremadura');
INSERT INTO District(name) VALUES ('California');
INSERT INTO District(name) VALUES ('District of Columbia');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Midi-Pyr�n�es');
INSERT INTO District(name) VALUES ('V�stra G�taland');
INSERT INTO District(name) VALUES ('Alberta');
INSERT INTO District(name) VALUES ('Alberta');
INSERT INTO District(name) VALUES ('Braga');
INSERT INTO District(name) VALUES ('Alberta');
INSERT INTO District(name) VALUES ('Ontario');
INSERT INTO District(name) VALUES ('Provence-Alpes-C�te d''Azur');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Guarda');
INSERT INTO District(name) VALUES ('Alaska');
INSERT INTO District(name) VALUES ('V�stra G�taland');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('Sarawak');
INSERT INTO District(name) VALUES ('Sonora');
INSERT INTO District(name) VALUES ('V�sterbotten');
INSERT INTO District(name) VALUES ('Guerrero');
INSERT INTO District(name) VALUES ('Santar�m');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('Franche-Comt�');
INSERT INTO District(name) VALUES ('Victoria');
INSERT INTO District(name) VALUES ('Porto');
INSERT INTO District(name) VALUES ('Baden-W�rttemberg');
INSERT INTO District(name) VALUES ('Guanajuato');
INSERT INTO District(name) VALUES ('Provincie Utrecht');
INSERT INTO District(name) VALUES ('Leiria');
INSERT INTO District(name) VALUES ('West Virginia');
INSERT INTO District(name) VALUES ('V�sterbotten');
INSERT INTO District(name) VALUES ('California');
INSERT INTO District(name) VALUES ('Sabah');
INSERT INTO District(name) VALUES ('Tennessee');
INSERT INTO District(name) VALUES ('Lorraine');
INSERT INTO District(name) VALUES ('Illinois');
INSERT INTO District(name) VALUES ('Set�bal');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('Aquitaine');
INSERT INTO District(name) VALUES ('Veracruz Llave');
INSERT INTO District(name) VALUES ('Coimbra');
INSERT INTO District(name) VALUES ('�sterg�tland');
INSERT INTO District(name) VALUES ('Porto');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('Provincie Friesland');
INSERT INTO District(name) VALUES ('Stockholm');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('Qu�bec');
INSERT INTO District(name) VALUES ('Andalucia');
INSERT INTO District(name) VALUES ('Florida');
INSERT INTO District(name) VALUES ('Braga');
INSERT INTO District(name) VALUES ('�sterg�tland');
INSERT INTO District(name) VALUES ('Porto');
INSERT INTO District(name) VALUES ('Porto');
INSERT INTO District(name) VALUES ('V�stra G�taland');
INSERT INTO District(name) VALUES ('�le-de-France');
INSERT INTO District(name) VALUES ('V�stra G�taland');
INSERT INTO District(name) VALUES ('North Carolina');
INSERT INTO District(name) VALUES ('Nordrhein-Westfalen');
INSERT INTO District(name) VALUES ('Viseu');
INSERT INTO District(name) VALUES ('V�stra G�taland');
