-- Cities - 2 000

INSERT INTO City(name) VALUES ('Skeldon');
INSERT INTO City(name) VALUES ('Lao Suea Kok');
INSERT INTO City(name) VALUES ('San Francisco');
INSERT INTO City(name) VALUES ('Shatian');
INSERT INTO City(name) VALUES ('E’erdun Wula');
INSERT INTO City(name) VALUES ('Maojiadian');
INSERT INTO City(name) VALUES ('Morfovoúni');
INSERT INTO City(name) VALUES ('Harper');
INSERT INTO City(name) VALUES ('Stavanger');
INSERT INTO City(name) VALUES ('Quilpué');
INSERT INTO City(name) VALUES ('Jacksonville');
INSERT INTO City(name) VALUES ('Ly? S?n');
INSERT INTO City(name) VALUES ('Keumala');
INSERT INTO City(name) VALUES ('Woshui');
INSERT INTO City(name) VALUES ('Dongping');
INSERT INTO City(name) VALUES ('San Pedro');
INSERT INTO City(name) VALUES ('Valbo');
INSERT INTO City(name) VALUES ('Vista Hermosa');
INSERT INTO City(name) VALUES ('Maredakalada');
INSERT INTO City(name) VALUES ('Tarusa');
INSERT INTO City(name) VALUES ('Banjarejo');
INSERT INTO City(name) VALUES ('Inuyama');
INSERT INTO City(name) VALUES ('Enskede');
INSERT INTO City(name) VALUES ('Gora');
INSERT INTO City(name) VALUES ('Potoru');
INSERT INTO City(name) VALUES ('Ardino');
INSERT INTO City(name) VALUES ('Shar');
INSERT INTO City(name) VALUES ('Ilioúpoli');
INSERT INTO City(name) VALUES ('Voskop');
INSERT INTO City(name) VALUES ('??i Ngô');
INSERT INTO City(name) VALUES ('Villa Lugano');
INSERT INTO City(name) VALUES ('Oshawa');
INSERT INTO City(name) VALUES ('Pombal');
INSERT INTO City(name) VALUES ('Tr?bki Wielkie');
INSERT INTO City(name) VALUES ('Milanów');
INSERT INTO City(name) VALUES ('Hats’avan');
INSERT INTO City(name) VALUES ('Al B?rah');
INSERT INTO City(name) VALUES ('Banjarejo');
INSERT INTO City(name) VALUES ('Campo Maior');
INSERT INTO City(name) VALUES ('Longzhouwan');
INSERT INTO City(name) VALUES ('Pau');
INSERT INTO City(name) VALUES ('Nanxing');
INSERT INTO City(name) VALUES ('Fulnek');
INSERT INTO City(name) VALUES ('Sacapulas');
INSERT INTO City(name) VALUES ('Valka');
INSERT INTO City(name) VALUES ('Kedian');
INSERT INTO City(name) VALUES ('Mokronog');
INSERT INTO City(name) VALUES ('Poxi');
INSERT INTO City(name) VALUES ('Hilversum');
INSERT INTO City(name) VALUES ('Leonárisso');
INSERT INTO City(name) VALUES ('Kawm Umb?');
INSERT INTO City(name) VALUES ('Savyntsi');
INSERT INTO City(name) VALUES ('Åkersberga');
INSERT INTO City(name) VALUES ('Cikandang');
INSERT INTO City(name) VALUES ('Krajan Suko Kidul');
INSERT INTO City(name) VALUES ('Ñuñoa');
INSERT INTO City(name) VALUES ('Lagoa do Itaenga');
INSERT INTO City(name) VALUES ('Mafinga');
INSERT INTO City(name) VALUES ('Arras');
INSERT INTO City(name) VALUES ('Donghe');
INSERT INTO City(name) VALUES ('Amiens');
INSERT INTO City(name) VALUES ('Yuantan');
INSERT INTO City(name) VALUES ('Masipi West');
INSERT INTO City(name) VALUES ('Rano');
INSERT INTO City(name) VALUES ('Zhetian');
INSERT INTO City(name) VALUES ('Santo Domingo de los Colorados');
INSERT INTO City(name) VALUES ('Jianfeng');
INSERT INTO City(name) VALUES ('Santarém');
INSERT INTO City(name) VALUES ('Rakszawa');
INSERT INTO City(name) VALUES ('Kuncen');
INSERT INTO City(name) VALUES ('Ourense');
INSERT INTO City(name) VALUES ('Ambatolaona');
INSERT INTO City(name) VALUES ('Antang');
INSERT INTO City(name) VALUES ('Guanban');
INSERT INTO City(name) VALUES ('Sizhou');
INSERT INTO City(name) VALUES ('Sugcad');
INSERT INTO City(name) VALUES ('Xin’an');
INSERT INTO City(name) VALUES ('Arapongas');
INSERT INTO City(name) VALUES ('San Francisco');
INSERT INTO City(name) VALUES ('Rengo');
INSERT INTO City(name) VALUES ('Igrejinha');
INSERT INTO City(name) VALUES ('Studzionka');
INSERT INTO City(name) VALUES ('Colombo');
INSERT INTO City(name) VALUES ('Izingolweni');
INSERT INTO City(name) VALUES ('Ribas do Rio Pardo');
INSERT INTO City(name) VALUES ('Qingquan');
INSERT INTO City(name) VALUES ('Wuyun');
INSERT INTO City(name) VALUES ('Taoyuan');
INSERT INTO City(name) VALUES ('Changleng');
INSERT INTO City(name) VALUES ('Kil');
INSERT INTO City(name) VALUES ('Podujeva');
INSERT INTO City(name) VALUES ('Gjilan');
INSERT INTO City(name) VALUES ('Wailebe');
INSERT INTO City(name) VALUES ('Asopía');
INSERT INTO City(name) VALUES ('Talu');
INSERT INTO City(name) VALUES ('Czernikowo');
INSERT INTO City(name) VALUES ('Qal‘at al Andalus');
INSERT INTO City(name) VALUES ('Daqian');
INSERT INTO City(name) VALUES ('São Vicente');
INSERT INTO City(name) VALUES ('Siuna');
INSERT INTO City(name) VALUES ('?tsuchi');
INSERT INTO City(name) VALUES ('L?c Bình');
INSERT INTO City(name) VALUES ('Salimbalan');
INSERT INTO City(name) VALUES ('Bayt ‘Aww?');
INSERT INTO City(name) VALUES ('Rustam jo Goth');
INSERT INTO City(name) VALUES ('Uchaly');
INSERT INTO City(name) VALUES ('Qazax');
INSERT INTO City(name) VALUES ('Arnhem');
INSERT INTO City(name) VALUES ('Nizao');
INSERT INTO City(name) VALUES ('Seoam');
INSERT INTO City(name) VALUES ('Grimshaw');
INSERT INTO City(name) VALUES ('Haibara');
INSERT INTO City(name) VALUES ('Leticia');
INSERT INTO City(name) VALUES ('Gaoxu');
INSERT INTO City(name) VALUES ('Dois Vizinhos');
INSERT INTO City(name) VALUES ('Katoúna');
INSERT INTO City(name) VALUES ('N?r?b?d');
INSERT INTO City(name) VALUES ('Sambirobyong');
INSERT INTO City(name) VALUES ('Béboto');
INSERT INTO City(name) VALUES ('Moutfort');
INSERT INTO City(name) VALUES ('Saint-Denis');
INSERT INTO City(name) VALUES ('Nanguzhuang');
INSERT INTO City(name) VALUES ('San Salvador');
INSERT INTO City(name) VALUES ('Arvika');
INSERT INTO City(name) VALUES ('Malabor');
INSERT INTO City(name) VALUES ('Alphen aan den Rijn');
INSERT INTO City(name) VALUES ('Jianguang');
INSERT INTO City(name) VALUES ('Dalan');
INSERT INTO City(name) VALUES ('Nizhniy Lomov');
INSERT INTO City(name) VALUES ('Bunia');
INSERT INTO City(name) VALUES ('Curibaya');
INSERT INTO City(name) VALUES ('Vancouver');
INSERT INTO City(name) VALUES ('Banjar Pande');
INSERT INTO City(name) VALUES ('Swords');
INSERT INTO City(name) VALUES ('Batouri');
INSERT INTO City(name) VALUES ('Metsovo');
INSERT INTO City(name) VALUES ('Noginsk');
INSERT INTO City(name) VALUES ('Kuvshinovo');
INSERT INTO City(name) VALUES ('Jingxi');
INSERT INTO City(name) VALUES ('Vanderbijlpark');
INSERT INTO City(name) VALUES ('Namalenga');
INSERT INTO City(name) VALUES ('Naberera');
INSERT INTO City(name) VALUES ('Aquidauana');
INSERT INTO City(name) VALUES ('Maketu');
INSERT INTO City(name) VALUES ('Ciekek');
INSERT INTO City(name) VALUES ('Popayán');
INSERT INTO City(name) VALUES ('K?my?r?n');
INSERT INTO City(name) VALUES ('Hefu');
INSERT INTO City(name) VALUES ('Perfilovo');
INSERT INTO City(name) VALUES ('Usukhchay');
INSERT INTO City(name) VALUES ('Karpacz');
INSERT INTO City(name) VALUES ('Pyrzyce');
INSERT INTO City(name) VALUES ('Porkhov');
INSERT INTO City(name) VALUES ('Maisí');
INSERT INTO City(name) VALUES ('Rio Branco do Sul');
INSERT INTO City(name) VALUES ('Las Sabanas');
INSERT INTO City(name) VALUES ('Perho');
INSERT INTO City(name) VALUES ('Washington');
INSERT INTO City(name) VALUES ('Changxing');
INSERT INTO City(name) VALUES ('Monte de Fralães');
INSERT INTO City(name) VALUES ('Matiao');
INSERT INTO City(name) VALUES ('Santa Cruz de Guacas');
INSERT INTO City(name) VALUES ('Monte Carmelo');
INSERT INTO City(name) VALUES ('Nianba');
INSERT INTO City(name) VALUES ('Kuala Lumpur');
INSERT INTO City(name) VALUES ('Minusinsk');
INSERT INTO City(name) VALUES ('Kedungdoro');
INSERT INTO City(name) VALUES ('Qom');
INSERT INTO City(name) VALUES ('Strasbourg');
INSERT INTO City(name) VALUES ('Lue Amnat');
INSERT INTO City(name) VALUES ('Taramana');
INSERT INTO City(name) VALUES ('Lansing');
INSERT INTO City(name) VALUES ('Beringin');
INSERT INTO City(name) VALUES ('Podsineye');
INSERT INTO City(name) VALUES ('Psará');
INSERT INTO City(name) VALUES ('Creil');
INSERT INTO City(name) VALUES ('Zheleznovodsk');
INSERT INTO City(name) VALUES ('Tovarkovskiy');
INSERT INTO City(name) VALUES ('Dongbatu');
INSERT INTO City(name) VALUES ('Riachos');
INSERT INTO City(name) VALUES ('Kandava');
INSERT INTO City(name) VALUES ('Linhares');
INSERT INTO City(name) VALUES ('Rosh Pinna');
INSERT INTO City(name) VALUES ('Imaichi');
INSERT INTO City(name) VALUES ('Bayanan');
INSERT INTO City(name) VALUES ('Ibaan');
INSERT INTO City(name) VALUES ('Stockholm');
INSERT INTO City(name) VALUES ('Amnat Charoen');
INSERT INTO City(name) VALUES ('Ilebo');
INSERT INTO City(name) VALUES ('Skhodnitsa');
INSERT INTO City(name) VALUES ('Tambo');
INSERT INTO City(name) VALUES ('Bariri');
INSERT INTO City(name) VALUES ('Slobodnica');
INSERT INTO City(name) VALUES ('Wentugaole');
INSERT INTO City(name) VALUES ('Caxias do Sul');
INSERT INTO City(name) VALUES ('Ku?evo');
INSERT INTO City(name) VALUES ('Fuli');
INSERT INTO City(name) VALUES ('Langensari');
INSERT INTO City(name) VALUES ('Yancheng');
INSERT INTO City(name) VALUES ('Karantaba');
INSERT INTO City(name) VALUES ('Cam Lâm');
INSERT INTO City(name) VALUES ('Bad?m?');
INSERT INTO City(name) VALUES ('Yasothon');
INSERT INTO City(name) VALUES ('Kampunglistrik');
INSERT INTO City(name) VALUES ('Sebulu');
INSERT INTO City(name) VALUES ('Susanino');
INSERT INTO City(name) VALUES ('Concepción');
INSERT INTO City(name) VALUES ('Odolanów');
INSERT INTO City(name) VALUES ('Makanya');
INSERT INTO City(name) VALUES ('Ferreiros');
INSERT INTO City(name) VALUES ('Fika');
INSERT INTO City(name) VALUES ('Guajiasi');
INSERT INTO City(name) VALUES ('Kisanga');
INSERT INTO City(name) VALUES ('Kumbo');
INSERT INTO City(name) VALUES ('Manorhamilton');
INSERT INTO City(name) VALUES ('Viana');
INSERT INTO City(name) VALUES ('Samdrup Jongkhar');
INSERT INTO City(name) VALUES ('Lubaczów');
INSERT INTO City(name) VALUES ('Salisbury');
INSERT INTO City(name) VALUES ('Oslo');
INSERT INTO City(name) VALUES ('Tiang');
INSERT INTO City(name) VALUES ('Hengdian');
INSERT INTO City(name) VALUES ('Washington');
INSERT INTO City(name) VALUES ('Sbo’o');
INSERT INTO City(name) VALUES ('Ramaram');
INSERT INTO City(name) VALUES ('Meiyuan');
INSERT INTO City(name) VALUES ('Bantal');
INSERT INTO City(name) VALUES ('København');
INSERT INTO City(name) VALUES ('Ciemas');
INSERT INTO City(name) VALUES ('Arcachon');
INSERT INTO City(name) VALUES ('Tasböget');
INSERT INTO City(name) VALUES ('Pecka');
INSERT INTO City(name) VALUES ('Sukowidodo Barat');
INSERT INTO City(name) VALUES ('Storuman');
INSERT INTO City(name) VALUES ('Palkovice');
INSERT INTO City(name) VALUES ('Sydney Mines');
INSERT INTO City(name) VALUES ('Yazman');
INSERT INTO City(name) VALUES ('Hvozdná');
INSERT INTO City(name) VALUES ('Tak?b');
INSERT INTO City(name) VALUES ('Kalayemule');
INSERT INTO City(name) VALUES ('My?lenice');
INSERT INTO City(name) VALUES ('Pompéu');
INSERT INTO City(name) VALUES ('Tuchola');
INSERT INTO City(name) VALUES ('Ulaandel');
INSERT INTO City(name) VALUES ('Eirunepé');
INSERT INTO City(name) VALUES ('Adh Dhayd');
INSERT INTO City(name) VALUES ('Ubá');
INSERT INTO City(name) VALUES ('Dimitrov');
INSERT INTO City(name) VALUES ('Plavy');
INSERT INTO City(name) VALUES ('Brondong');
INSERT INTO City(name) VALUES ('Lübeck');
INSERT INTO City(name) VALUES ('Xirikxiy');
INSERT INTO City(name) VALUES ('Wangbuzhuang');
INSERT INTO City(name) VALUES ('Cimara');
INSERT INTO City(name) VALUES ('Mae Hi');
INSERT INTO City(name) VALUES ('Rancapanjang');
INSERT INTO City(name) VALUES ('Koszarawa');
INSERT INTO City(name) VALUES ('Kui Buri');
INSERT INTO City(name) VALUES ('São Lourenço do Sul');
INSERT INTO City(name) VALUES ('?hm?db?yli');
INSERT INTO City(name) VALUES ('Pantanal');
INSERT INTO City(name) VALUES ('Koper');
INSERT INTO City(name) VALUES ('Palana');
INSERT INTO City(name) VALUES ('Vostryakovo');
INSERT INTO City(name) VALUES ('Mamboma');
INSERT INTO City(name) VALUES ('Madrid');
INSERT INTO City(name) VALUES ('Nginjen');
INSERT INTO City(name) VALUES ('Pho Thong');
INSERT INTO City(name) VALUES ('Bystra');
INSERT INTO City(name) VALUES ('Alverca do Ribatejo');
INSERT INTO City(name) VALUES ('Hinthada');
INSERT INTO City(name) VALUES ('Zhangye');
INSERT INTO City(name) VALUES ('Stepnica');
INSERT INTO City(name) VALUES ('Cubará');
INSERT INTO City(name) VALUES ('Chai Badan');
INSERT INTO City(name) VALUES ('Hpa-an');
INSERT INTO City(name) VALUES ('Tongzha');
INSERT INTO City(name) VALUES ('Puutura');
INSERT INTO City(name) VALUES ('Ursk');
INSERT INTO City(name) VALUES ('Dobrzyca');
INSERT INTO City(name) VALUES ('Wi?lica');
INSERT INTO City(name) VALUES ('Shi?an as Suflá');
INSERT INTO City(name) VALUES ('Agadez');
INSERT INTO City(name) VALUES ('Qijing');
INSERT INTO City(name) VALUES ('Dolní ?ermná');
INSERT INTO City(name) VALUES ('Malianzhuang');
INSERT INTO City(name) VALUES ('Terek');
INSERT INTO City(name) VALUES ('Situ');
INSERT INTO City(name) VALUES ('Santiago del Torno');
INSERT INTO City(name) VALUES ('Menlou’ao');
INSERT INTO City(name) VALUES ('Salamrejo');
INSERT INTO City(name) VALUES ('Bassila');
INSERT INTO City(name) VALUES ('?????????');
INSERT INTO City(name) VALUES ('Qiaochong');
INSERT INTO City(name) VALUES ('Johor Bahru');
INSERT INTO City(name) VALUES ('Tubualá');
INSERT INTO City(name) VALUES ('Siwa Oasis');
INSERT INTO City(name) VALUES ('Mykolayiv');
INSERT INTO City(name) VALUES ('Panórama');
INSERT INTO City(name) VALUES ('Villa Nueva');
INSERT INTO City(name) VALUES ('Hässleholm');
INSERT INTO City(name) VALUES ('Communal');
INSERT INTO City(name) VALUES ('Wielbark');
INSERT INTO City(name) VALUES ('Phoenix');
INSERT INTO City(name) VALUES ('Kariaí');
INSERT INTO City(name) VALUES ('Vilca');
INSERT INTO City(name) VALUES ('Lujiao');
INSERT INTO City(name) VALUES ('Néa Manolás');
INSERT INTO City(name) VALUES ('Worcester');
INSERT INTO City(name) VALUES ('Angoulême');
INSERT INTO City(name) VALUES ('Yuewan');
INSERT INTO City(name) VALUES ('Munkfors');
INSERT INTO City(name) VALUES ('Targanice');
INSERT INTO City(name) VALUES ('Lastoursville');
INSERT INTO City(name) VALUES ('Fovissste');
INSERT INTO City(name) VALUES ('Lanzhong');
INSERT INTO City(name) VALUES ('Itapira');
INSERT INTO City(name) VALUES ('Fak Tha');
INSERT INTO City(name) VALUES ('Hexing');
INSERT INTO City(name) VALUES ('Strasbourg');
INSERT INTO City(name) VALUES ('Wulipu');
INSERT INTO City(name) VALUES ('Seremban');
INSERT INTO City(name) VALUES ('Zafarw?l');
INSERT INTO City(name) VALUES ('Komysh-Zorya');
INSERT INTO City(name) VALUES ('Skien');
INSERT INTO City(name) VALUES ('Buchach');
INSERT INTO City(name) VALUES ('Xuelu');
INSERT INTO City(name) VALUES ('Varva');
INSERT INTO City(name) VALUES ('Zumarraga');
INSERT INTO City(name) VALUES ('Sujji');
INSERT INTO City(name) VALUES ('Vilkaviskis');
INSERT INTO City(name) VALUES ('Kohlu');
INSERT INTO City(name) VALUES ('H??ng S?n');
INSERT INTO City(name) VALUES ('Nîmes');
INSERT INTO City(name) VALUES ('Pelem');
INSERT INTO City(name) VALUES ('Magallanes');
INSERT INTO City(name) VALUES ('Dubrovka');
INSERT INTO City(name) VALUES ('Mae Charim');
INSERT INTO City(name) VALUES ('Trelleborg');
INSERT INTO City(name) VALUES ('Fengyuan');
INSERT INTO City(name) VALUES ('Estancia');
INSERT INTO City(name) VALUES ('Nancaicun');
INSERT INTO City(name) VALUES ('Shirochanka');
INSERT INTO City(name) VALUES ('Prang Ku');
INSERT INTO City(name) VALUES ('Alabug');
INSERT INTO City(name) VALUES ('Rembes');
INSERT INTO City(name) VALUES ('Taoyuan');
INSERT INTO City(name) VALUES ('Pimentel');
INSERT INTO City(name) VALUES ('Duanjia');
INSERT INTO City(name) VALUES ('Guanyinsi');
INSERT INTO City(name) VALUES ('Paris La Défense');
INSERT INTO City(name) VALUES ('Duoxiang');
INSERT INTO City(name) VALUES ('Tikiw');
INSERT INTO City(name) VALUES ('Laç');
INSERT INTO City(name) VALUES ('Didian');
INSERT INTO City(name) VALUES ('Ershilipu');
INSERT INTO City(name) VALUES ('Trunovskoye');
INSERT INTO City(name) VALUES ('Stutterheim');
INSERT INTO City(name) VALUES ('Niort');
INSERT INTO City(name) VALUES ('Anse Royale');
INSERT INTO City(name) VALUES ('Nyala');
INSERT INTO City(name) VALUES ('Gaillac');
INSERT INTO City(name) VALUES ('Regnów');
INSERT INTO City(name) VALUES ('Tanjungluar');
INSERT INTO City(name) VALUES ('Tirana');
INSERT INTO City(name) VALUES ('Paracatu');
INSERT INTO City(name) VALUES ('Colcabamba');
INSERT INTO City(name) VALUES ('Sanhu');
INSERT INTO City(name) VALUES ('Balboa');
INSERT INTO City(name) VALUES ('Wlingi');
INSERT INTO City(name) VALUES ('Gwadabawa');
INSERT INTO City(name) VALUES ('Qiganjidie');
INSERT INTO City(name) VALUES ('Álli Meriá');
INSERT INTO City(name) VALUES ('Fuchun');
INSERT INTO City(name) VALUES ('Lanas');
INSERT INTO City(name) VALUES ('Sofádes');
INSERT INTO City(name) VALUES ('Tongyu');
INSERT INTO City(name) VALUES ('Qinghaihu');
INSERT INTO City(name) VALUES ('Santisimo Rosario');
INSERT INTO City(name) VALUES ('Ligonggang');
INSERT INTO City(name) VALUES ('Zhongcun');
INSERT INTO City(name) VALUES ('Arrepiado');
INSERT INTO City(name) VALUES ('Firmat');
INSERT INTO City(name) VALUES ('Baisha');
INSERT INTO City(name) VALUES ('Boka');
INSERT INTO City(name) VALUES ('Cabreúva');
INSERT INTO City(name) VALUES ('Chernivtsi');
INSERT INTO City(name) VALUES ('Samho-rodongjagu');
INSERT INTO City(name) VALUES ('Karlivka');
INSERT INTO City(name) VALUES ('Tala');
INSERT INTO City(name) VALUES ('Konstantinovsk');
INSERT INTO City(name) VALUES ('Katipunan');
INSERT INTO City(name) VALUES ('Hausjärvi');
INSERT INTO City(name) VALUES ('Bykivka');
INSERT INTO City(name) VALUES ('Pancas');
INSERT INTO City(name) VALUES ('Paraíso');
INSERT INTO City(name) VALUES ('Khlong Yai');
INSERT INTO City(name) VALUES ('Tchoban Bey');
INSERT INTO City(name) VALUES ('Krasnyy Kholm');
INSERT INTO City(name) VALUES ('Charata');
INSERT INTO City(name) VALUES ('Lebyazh’ye');
INSERT INTO City(name) VALUES ('Yiwa');
INSERT INTO City(name) VALUES ('Roanne');
INSERT INTO City(name) VALUES ('Haicheng');
INSERT INTO City(name) VALUES ('Örebro');
INSERT INTO City(name) VALUES ('Quezon');
INSERT INTO City(name) VALUES ('Chahe');
INSERT INTO City(name) VALUES ('Rora Timur');
INSERT INTO City(name) VALUES ('Riberalta');
INSERT INTO City(name) VALUES ('Vitanje');
INSERT INTO City(name) VALUES ('Paraíso');
INSERT INTO City(name) VALUES ('Yumendong');
INSERT INTO City(name) VALUES ('Mevo horon');
INSERT INTO City(name) VALUES ('Buliwao');
INSERT INTO City(name) VALUES ('Tanabi');
INSERT INTO City(name) VALUES ('Dijon');
INSERT INTO City(name) VALUES ('Farafangana');
INSERT INTO City(name) VALUES ('Asemanis');
INSERT INTO City(name) VALUES ('Huaiyuan Chengguanzhen');
INSERT INTO City(name) VALUES ('Vingåker');
INSERT INTO City(name) VALUES ('Xiangzikou');
INSERT INTO City(name) VALUES ('Qasr Abu Hadi');
INSERT INTO City(name) VALUES ('Ba?kowice');
INSERT INTO City(name) VALUES ('‘Amd');
INSERT INTO City(name) VALUES ('Putang');
INSERT INTO City(name) VALUES ('Yako');
INSERT INTO City(name) VALUES ('Gudja');
INSERT INTO City(name) VALUES ('Fylí');
INSERT INTO City(name) VALUES ('Shahrak');
INSERT INTO City(name) VALUES ('Krajandadapmulyo');
INSERT INTO City(name) VALUES ('Futuroscope');
INSERT INTO City(name) VALUES ('Piekielnik');
INSERT INTO City(name) VALUES ('Gombong');
INSERT INTO City(name) VALUES ('Talagante');
INSERT INTO City(name) VALUES ('Presidencia Roque Sáenz Peña');
INSERT INTO City(name) VALUES ('Dagang');
INSERT INTO City(name) VALUES ('Shiyaogou');
INSERT INTO City(name) VALUES ('Luozhuang');
INSERT INTO City(name) VALUES ('Silago');
INSERT INTO City(name) VALUES ('Yanai');
INSERT INTO City(name) VALUES ('?irr?n ash Sham?l?yah');
INSERT INTO City(name) VALUES ('Uwa');
INSERT INTO City(name) VALUES ('Sattahip');
INSERT INTO City(name) VALUES ('Temryuk');
INSERT INTO City(name) VALUES ('Wujiayao');
INSERT INTO City(name) VALUES ('Mestre');
INSERT INTO City(name) VALUES ('Gaotieling');
INSERT INTO City(name) VALUES ('Redcliff');
INSERT INTO City(name) VALUES ('Benešov nad ?ernou');
INSERT INTO City(name) VALUES ('Krynychky');
INSERT INTO City(name) VALUES ('Doug An');
INSERT INTO City(name) VALUES ('Kariat Arkmane');
INSERT INTO City(name) VALUES ('Abuxarda');
INSERT INTO City(name) VALUES ('Espérance Trébuchet');
INSERT INTO City(name) VALUES ('Cuba');
INSERT INTO City(name) VALUES ('Lobamba');
INSERT INTO City(name) VALUES ('Langensari');
INSERT INTO City(name) VALUES ('?aydn?y?');
INSERT INTO City(name) VALUES ('Agidel’');
INSERT INTO City(name) VALUES ('Foso');
INSERT INTO City(name) VALUES ('Nartkala');
INSERT INTO City(name) VALUES ('Kaseda-shirakame');
INSERT INTO City(name) VALUES ('Rio Pardo');
INSERT INTO City(name) VALUES ('Saint Ann’s Bay');
INSERT INTO City(name) VALUES ('Seremban');
INSERT INTO City(name) VALUES ('Be?ej');
INSERT INTO City(name) VALUES ('El Corozo');
INSERT INTO City(name) VALUES ('Lohong');
INSERT INTO City(name) VALUES ('Florencia');
INSERT INTO City(name) VALUES ('Tyumen');
INSERT INTO City(name) VALUES ('Além do Rio');
INSERT INTO City(name) VALUES ('Dobra');
INSERT INTO City(name) VALUES ('Ki?evo');
INSERT INTO City(name) VALUES ('Khu Khan');
INSERT INTO City(name) VALUES ('Brejoeira');
INSERT INTO City(name) VALUES ('Houndé');
INSERT INTO City(name) VALUES ('Veshnyaki');
INSERT INTO City(name) VALUES ('Llorente');
INSERT INTO City(name) VALUES ('Gyamco');
INSERT INTO City(name) VALUES ('Selaphum');
INSERT INTO City(name) VALUES ('Buturlinovka');
INSERT INTO City(name) VALUES ('Gunung');
INSERT INTO City(name) VALUES ('Houping');
INSERT INTO City(name) VALUES ('Soloma');
INSERT INTO City(name) VALUES ('Marseille');
INSERT INTO City(name) VALUES ('Baranusa');
INSERT INTO City(name) VALUES ('Askersund');
INSERT INTO City(name) VALUES ('Cerklje na Gorenjskem');
INSERT INTO City(name) VALUES ('Luleå');
INSERT INTO City(name) VALUES ('Karajeun');
INSERT INTO City(name) VALUES ('Santiago De Compostela');
INSERT INTO City(name) VALUES ('Francisco Villa');
INSERT INTO City(name) VALUES ('Kuntong');
INSERT INTO City(name) VALUES ('Sukonolo Krajan');
INSERT INTO City(name) VALUES ('Novodmitriyevskaya');
INSERT INTO City(name) VALUES ('Pinillos');
INSERT INTO City(name) VALUES ('Pruchnik');
INSERT INTO City(name) VALUES ('Madala');
INSERT INTO City(name) VALUES ('?iso');
INSERT INTO City(name) VALUES ('Przyborów');
INSERT INTO City(name) VALUES ('Andahuaylillas');
INSERT INTO City(name) VALUES ('Gävle');
INSERT INTO City(name) VALUES ('Jatiklampok');
INSERT INTO City(name) VALUES ('Buenavista');
INSERT INTO City(name) VALUES ('Vitim');
INSERT INTO City(name) VALUES ('Sho’rchi');
INSERT INTO City(name) VALUES ('Yevpatoriya');
INSERT INTO City(name) VALUES ('Th? Tr?n Thu?n Châu');
INSERT INTO City(name) VALUES ('Telagasari');
INSERT INTO City(name) VALUES ('Cigadung');
INSERT INTO City(name) VALUES ('Oslo');
INSERT INTO City(name) VALUES ('São Caetano do Sul');
INSERT INTO City(name) VALUES ('Hantsavichy');
INSERT INTO City(name) VALUES ('Árta');
INSERT INTO City(name) VALUES ('Hoery?ng');
INSERT INTO City(name) VALUES ('Méru');
INSERT INTO City(name) VALUES ('Hong’an');
INSERT INTO City(name) VALUES ('Arpajon');
INSERT INTO City(name) VALUES ('Dan Sadau');
INSERT INTO City(name) VALUES ('Cordova');
INSERT INTO City(name) VALUES ('Kaura Namoda');
INSERT INTO City(name) VALUES ('Agbor');
INSERT INTO City(name) VALUES ('T?kest?n');
INSERT INTO City(name) VALUES ('Zhicheng');
INSERT INTO City(name) VALUES ('Portariá');
INSERT INTO City(name) VALUES ('La Viña');
INSERT INTO City(name) VALUES ('Calaba');
INSERT INTO City(name) VALUES ('Nu’erbage');
INSERT INTO City(name) VALUES ('Ngaoundéré');
INSERT INTO City(name) VALUES ('Quva');
INSERT INTO City(name) VALUES ('Le?nica');
INSERT INTO City(name) VALUES ('Pacarkeling');
INSERT INTO City(name) VALUES ('Gotse Delchev');
INSERT INTO City(name) VALUES ('Pecna');
INSERT INTO City(name) VALUES ('Mogi Mirim');
INSERT INTO City(name) VALUES ('Botou');
INSERT INTO City(name) VALUES ('Thu?n Nam');
INSERT INTO City(name) VALUES ('Chame');
INSERT INTO City(name) VALUES ('Chenguang');
INSERT INTO City(name) VALUES ('Varva');
INSERT INTO City(name) VALUES ('Quimper');
INSERT INTO City(name) VALUES ('Heredia');
INSERT INTO City(name) VALUES ('F?men?n');
INSERT INTO City(name) VALUES ('Saratov');
INSERT INTO City(name) VALUES ('Leshan');
INSERT INTO City(name) VALUES ('Vanáton');
INSERT INTO City(name) VALUES ('San Bernardino');
INSERT INTO City(name) VALUES ('Maceo');
INSERT INTO City(name) VALUES ('N???yat Saddat al Hind?yah');
INSERT INTO City(name) VALUES ('Sadabumi');
INSERT INTO City(name) VALUES ('Lidköping');
INSERT INTO City(name) VALUES ('Cela');
INSERT INTO City(name) VALUES ('Hongshunli');
INSERT INTO City(name) VALUES ('Parlilitan');
INSERT INTO City(name) VALUES ('Farkaždin');
INSERT INTO City(name) VALUES ('Bor Ondor');
INSERT INTO City(name) VALUES ('Sangumata');
INSERT INTO City(name) VALUES ('Cordeirópolis');
INSERT INTO City(name) VALUES ('Nanxing');
INSERT INTO City(name) VALUES ('Petrolina');
INSERT INTO City(name) VALUES ('Mulyoagung');
INSERT INTO City(name) VALUES ('Gostivar');
INSERT INTO City(name) VALUES ('Tambobamba');
INSERT INTO City(name) VALUES ('Tigbao');
INSERT INTO City(name) VALUES ('Manoc-Manoc');
INSERT INTO City(name) VALUES ('D?r? al Qar‘');
INSERT INTO City(name) VALUES ('Oklahoma City');
INSERT INTO City(name) VALUES ('Miami Beach');
INSERT INTO City(name) VALUES ('Koltushi');
INSERT INTO City(name) VALUES ('Banjar Dukuh');
INSERT INTO City(name) VALUES ('Tudela');
INSERT INTO City(name) VALUES ('Donghai');
INSERT INTO City(name) VALUES ('Enrekang');
INSERT INTO City(name) VALUES ('Nanshi');
INSERT INTO City(name) VALUES ('Lubniewice');
INSERT INTO City(name) VALUES ('Washington');
INSERT INTO City(name) VALUES ('Karamat');
INSERT INTO City(name) VALUES ('Ujar');
INSERT INTO City(name) VALUES ('Tabogon');
INSERT INTO City(name) VALUES ('Guansheng');
INSERT INTO City(name) VALUES ('Hagerstown');
INSERT INTO City(name) VALUES ('Luleå');
INSERT INTO City(name) VALUES ('Schaumburg');
INSERT INTO City(name) VALUES ('Oughterard');
INSERT INTO City(name) VALUES ('Rybarzowice');
INSERT INTO City(name) VALUES ('Khlevnoye');
INSERT INTO City(name) VALUES ('Beau Vallon');
INSERT INTO City(name) VALUES ('Osório');
INSERT INTO City(name) VALUES ('Talangbetutu');
INSERT INTO City(name) VALUES ('Las Vegas');
INSERT INTO City(name) VALUES ('Yang Chum Noi');
INSERT INTO City(name) VALUES ('Reston');
INSERT INTO City(name) VALUES ('Cahors');
INSERT INTO City(name) VALUES ('Rantaupanjangkiri');
INSERT INTO City(name) VALUES ('Yangjia');
INSERT INTO City(name) VALUES ('Gongming');
INSERT INTO City(name) VALUES ('Pangushan');
INSERT INTO City(name) VALUES ('Santa Teresa First');
INSERT INTO City(name) VALUES ('Bahir Dar');
INSERT INTO City(name) VALUES ('Changting');
INSERT INTO City(name) VALUES ('Miyata');
INSERT INTO City(name) VALUES ('Laguilayan');
INSERT INTO City(name) VALUES ('Kolodeznyy');
INSERT INTO City(name) VALUES ('Jati');
INSERT INTO City(name) VALUES ('Buyunshan');
INSERT INTO City(name) VALUES ('Nancheng');
INSERT INTO City(name) VALUES ('Khon San');
INSERT INTO City(name) VALUES ('Bowen Island');
INSERT INTO City(name) VALUES ('Nsanje');
INSERT INTO City(name) VALUES ('Stulovo');
INSERT INTO City(name) VALUES ('La Plaine-Saint-Denis');
INSERT INTO City(name) VALUES ('Munkedal');
INSERT INTO City(name) VALUES ('Baimi');
INSERT INTO City(name) VALUES ('Tenggun Dajah');
INSERT INTO City(name) VALUES ('Aengceleng');
INSERT INTO City(name) VALUES ('Qu?nh Côi');
INSERT INTO City(name) VALUES ('Gengcheng');
INSERT INTO City(name) VALUES ('Žihle');
INSERT INTO City(name) VALUES ('Xinzhaiping');
INSERT INTO City(name) VALUES ('Kolonia Town');
INSERT INTO City(name) VALUES ('Spiczyn');
INSERT INTO City(name) VALUES ('Rosh Pinna');
INSERT INTO City(name) VALUES ('Masoyila');
INSERT INTO City(name) VALUES ('Asahi');
INSERT INTO City(name) VALUES ('Ruzayevka');
INSERT INTO City(name) VALUES ('Kacha');
INSERT INTO City(name) VALUES ('Quintas');
INSERT INTO City(name) VALUES ('Half Way Tree');
INSERT INTO City(name) VALUES ('Chunhua');
INSERT INTO City(name) VALUES ('Chengbei');
INSERT INTO City(name) VALUES ('Yong’an');
INSERT INTO City(name) VALUES ('Aleksinac');
INSERT INTO City(name) VALUES ('Hohoe');
INSERT INTO City(name) VALUES ('Cabangan');
INSERT INTO City(name) VALUES ('Singajaya');
INSERT INTO City(name) VALUES ('Ustrzyki Dolne');
INSERT INTO City(name) VALUES ('Évry');
INSERT INTO City(name) VALUES ('Nagahama');
INSERT INTO City(name) VALUES ('Huangtian');
INSERT INTO City(name) VALUES ('Cantao-an');
INSERT INTO City(name) VALUES ('Chixi');
INSERT INTO City(name) VALUES ('Hongtang');
INSERT INTO City(name) VALUES ('Bagadó');
INSERT INTO City(name) VALUES ('Uppsala');
INSERT INTO City(name) VALUES ('Kudang');
INSERT INTO City(name) VALUES ('Kulun');
INSERT INTO City(name) VALUES ('Pandat');
INSERT INTO City(name) VALUES ('Mar?dah');
INSERT INTO City(name) VALUES ('Santa Justina');
INSERT INTO City(name) VALUES ('Eadestown');
INSERT INTO City(name) VALUES ('Patos de Minas');
INSERT INTO City(name) VALUES ('Villasis');
INSERT INTO City(name) VALUES ('Su-ngai Kolok');
INSERT INTO City(name) VALUES ('Alcácer do Sal');
INSERT INTO City(name) VALUES ('Ra?e');
INSERT INTO City(name) VALUES ('Bandarbeyla');
INSERT INTO City(name) VALUES ('Val-de-Reuil');
INSERT INTO City(name) VALUES ('Guta');
INSERT INTO City(name) VALUES ('Chikeng');
INSERT INTO City(name) VALUES ('Amagasaki');
INSERT INTO City(name) VALUES ('Las Matas de Farfán');
INSERT INTO City(name) VALUES ('Émpa');
INSERT INTO City(name) VALUES ('Sukamulya');
INSERT INTO City(name) VALUES ('Dire Dawa');
INSERT INTO City(name) VALUES ('Yosowilangun');
INSERT INTO City(name) VALUES ('Kefar Shemaryahu');
INSERT INTO City(name) VALUES ('Florianópolis');
INSERT INTO City(name) VALUES ('Artemisa');
INSERT INTO City(name) VALUES ('Zhangdian');
INSERT INTO City(name) VALUES ('Baoshan');
INSERT INTO City(name) VALUES ('Yantan');
INSERT INTO City(name) VALUES ('Loukhi');
INSERT INTO City(name) VALUES ('Tabango');
INSERT INTO City(name) VALUES ('Végueta');
INSERT INTO City(name) VALUES ('Alphen aan den Rijn');
INSERT INTO City(name) VALUES ('Xiyuan');
INSERT INTO City(name) VALUES ('Jackson');
INSERT INTO City(name) VALUES ('Veracruz');
INSERT INTO City(name) VALUES ('Sumbersari Wetan');
INSERT INTO City(name) VALUES ('Paris 02');
INSERT INTO City(name) VALUES ('Sukamulya');
INSERT INTO City(name) VALUES ('Yahe');
INSERT INTO City(name) VALUES ('Bunga Mas');
INSERT INTO City(name) VALUES ('?sht??n');
INSERT INTO City(name) VALUES ('La Charité-sur-Loire');
INSERT INTO City(name) VALUES ('Pouébo');
INSERT INTO City(name) VALUES ('Sukogunungkrajan');
INSERT INTO City(name) VALUES ('Ra?ad');
INSERT INTO City(name) VALUES ('Tajr?sh');
INSERT INTO City(name) VALUES ('Oodweyne');
INSERT INTO City(name) VALUES ('Extrema');
INSERT INTO City(name) VALUES ('Awayan');
INSERT INTO City(name) VALUES ('Firavitoba');
INSERT INTO City(name) VALUES ('Jatirejo');
INSERT INTO City(name) VALUES ('Domanín');
INSERT INTO City(name) VALUES ('Char Bhadr?san');
INSERT INTO City(name) VALUES ('‘Izr?');
INSERT INTO City(name) VALUES ('San Carlos');
INSERT INTO City(name) VALUES ('Sirnaresmi');
INSERT INTO City(name) VALUES ('G?dol?');
INSERT INTO City(name) VALUES ('Indaial');
INSERT INTO City(name) VALUES ('Dongping');
INSERT INTO City(name) VALUES ('Fukadale');
INSERT INTO City(name) VALUES ('Fika');
INSERT INTO City(name) VALUES ('Kävlinge');
INSERT INTO City(name) VALUES ('Ust’-Ilimsk');
INSERT INTO City(name) VALUES ('Acevedo');
INSERT INTO City(name) VALUES ('Airmadidi');
INSERT INTO City(name) VALUES ('Parczew');
INSERT INTO City(name) VALUES ('Lahad Datu');
INSERT INTO City(name) VALUES ('Savitaipale');
INSERT INTO City(name) VALUES ('Avarua');
INSERT INTO City(name) VALUES ('Gevgelija');
INSERT INTO City(name) VALUES ('Banag');
INSERT INTO City(name) VALUES ('Claveria');
INSERT INTO City(name) VALUES ('Nyköping');
INSERT INTO City(name) VALUES ('Los Angeles');
INSERT INTO City(name) VALUES ('Tanglag');
INSERT INTO City(name) VALUES ('Th? Xã Lai Châu');
INSERT INTO City(name) VALUES ('Bassar');
INSERT INTO City(name) VALUES ('Forécariah');
INSERT INTO City(name) VALUES ('Sophia Antipolis');
INSERT INTO City(name) VALUES ('Xushuguan');
INSERT INTO City(name) VALUES ('Mullsjö');
INSERT INTO City(name) VALUES ('Mitzpe Ramon');
INSERT INTO City(name) VALUES ('Kendalngupuk');
INSERT INTO City(name) VALUES ('Stockholm');
INSERT INTO City(name) VALUES ('Providencia');
INSERT INTO City(name) VALUES ('Mertert');
INSERT INTO City(name) VALUES ('Manhumirim');
INSERT INTO City(name) VALUES ('Vypolzovo');
INSERT INTO City(name) VALUES ('Beringinjaya');
INSERT INTO City(name) VALUES ('Krajan Menggare');
INSERT INTO City(name) VALUES ('Kamenné Žehrovice');
INSERT INTO City(name) VALUES ('Hualmay');
INSERT INTO City(name) VALUES ('Ervedosa do Douro');
INSERT INTO City(name) VALUES ('Saint Petersburg');
INSERT INTO City(name) VALUES ('Kasreman Wetan');
INSERT INTO City(name) VALUES ('Na Khu');
INSERT INTO City(name) VALUES ('Mlalo');
INSERT INTO City(name) VALUES ('Sui’an');
INSERT INTO City(name) VALUES ('Perjuangan');
INSERT INTO City(name) VALUES ('Iwakuni');
INSERT INTO City(name) VALUES ('Muyi');
INSERT INTO City(name) VALUES ('Pingshan');
INSERT INTO City(name) VALUES ('San Calixto');
INSERT INTO City(name) VALUES ('Phu Loc');
INSERT INTO City(name) VALUES ('Wierzbica');
INSERT INTO City(name) VALUES ('Sedlarevo');
INSERT INTO City(name) VALUES ('Vasil’yevskiy Mokh');
INSERT INTO City(name) VALUES ('Pataias');
INSERT INTO City(name) VALUES ('San Luis');
INSERT INTO City(name) VALUES ('Tippi');
INSERT INTO City(name) VALUES ('Hongxing');
INSERT INTO City(name) VALUES ('Kelapa');
INSERT INTO City(name) VALUES ('Lochovice');
INSERT INTO City(name) VALUES ('Khong');
INSERT INTO City(name) VALUES ('Chengjiang');
INSERT INTO City(name) VALUES ('Cabrobó');
INSERT INTO City(name) VALUES ('Lysyanka');
INSERT INTO City(name) VALUES ('Rude');
INSERT INTO City(name) VALUES ('Loket');
INSERT INTO City(name) VALUES ('Pata');
INSERT INTO City(name) VALUES ('Saint George''s');
INSERT INTO City(name) VALUES ('Proptisht');
INSERT INTO City(name) VALUES ('Gagah');
INSERT INTO City(name) VALUES ('Xiaoyangqi');
INSERT INTO City(name) VALUES ('Ilinden');
INSERT INTO City(name) VALUES ('Sogcho');
INSERT INTO City(name) VALUES ('Longping');
INSERT INTO City(name) VALUES ('Vilhelmina');
INSERT INTO City(name) VALUES ('Vereshchagino');
INSERT INTO City(name) VALUES ('Pandak');
INSERT INTO City(name) VALUES ('Dijon');
INSERT INTO City(name) VALUES ('Saint Catherine');
INSERT INTO City(name) VALUES ('Montrouge');
INSERT INTO City(name) VALUES ('Soweto');
INSERT INTO City(name) VALUES ('Verin Dvin');
INSERT INTO City(name) VALUES ('Lat Yao');
INSERT INTO City(name) VALUES ('Pantang');
INSERT INTO City(name) VALUES ('Vanves');
INSERT INTO City(name) VALUES ('Tshela');
INSERT INTO City(name) VALUES ('Castres');
INSERT INTO City(name) VALUES ('Kinalaglagan');
INSERT INTO City(name) VALUES ('Colmar');
INSERT INTO City(name) VALUES ('Borås');
INSERT INTO City(name) VALUES ('Pringgoboyo');
INSERT INTO City(name) VALUES ('Vredenburg');
INSERT INTO City(name) VALUES ('Båstad');
INSERT INTO City(name) VALUES ('Ban Ratsada');
INSERT INTO City(name) VALUES ('El Cantón');
INSERT INTO City(name) VALUES ('Tuqiao');
INSERT INTO City(name) VALUES ('Porto Seguro');
INSERT INTO City(name) VALUES ('Langtang');
INSERT INTO City(name) VALUES ('Tataouine');
INSERT INTO City(name) VALUES ('Don Chedi');
INSERT INTO City(name) VALUES ('San Isidro');
INSERT INTO City(name) VALUES ('Cibunar');
INSERT INTO City(name) VALUES ('Jind?ich?v Hradec');
INSERT INTO City(name) VALUES ('Damanh?r');
INSERT INTO City(name) VALUES ('Dovhe');
INSERT INTO City(name) VALUES ('Pingkai');
INSERT INTO City(name) VALUES ('Tazhuang');
INSERT INTO City(name) VALUES ('Pengilon');
INSERT INTO City(name) VALUES ('Mokotów');
INSERT INTO City(name) VALUES ('Zabierzów');
INSERT INTO City(name) VALUES ('Paris 15');
INSERT INTO City(name) VALUES ('Villaviciosa');
INSERT INTO City(name) VALUES ('Zakamensk');
INSERT INTO City(name) VALUES ('Rennes');
INSERT INTO City(name) VALUES ('Gulrip’shi');
INSERT INTO City(name) VALUES ('Tasböget');
INSERT INTO City(name) VALUES ('Bahorí');
INSERT INTO City(name) VALUES ('Piritiba');
INSERT INTO City(name) VALUES ('Nîmes');
INSERT INTO City(name) VALUES ('Mazhu');
INSERT INTO City(name) VALUES ('Chulabhorn');
INSERT INTO City(name) VALUES ('Airuk');
INSERT INTO City(name) VALUES ('Szombathely');
INSERT INTO City(name) VALUES ('Almendra');
INSERT INTO City(name) VALUES ('Gongnong');
INSERT INTO City(name) VALUES ('Taibai');
INSERT INTO City(name) VALUES ('Melaka');
INSERT INTO City(name) VALUES ('Kus?ng');
INSERT INTO City(name) VALUES ('Buy');
INSERT INTO City(name) VALUES ('Pingling');
INSERT INTO City(name) VALUES ('Barru');
INSERT INTO City(name) VALUES ('Espírito Santo do Pinhal');
INSERT INTO City(name) VALUES ('Cachoeirinha');
INSERT INTO City(name) VALUES ('Wakiso');
INSERT INTO City(name) VALUES ('Longmen');
INSERT INTO City(name) VALUES ('Seto');
INSERT INTO City(name) VALUES ('Puntaru');
INSERT INTO City(name) VALUES ('Xinglin');
INSERT INTO City(name) VALUES ('Santa Rita');
INSERT INTO City(name) VALUES ('Golopau');
INSERT INTO City(name) VALUES ('Odivelas');
INSERT INTO City(name) VALUES ('Ushibuka');
INSERT INTO City(name) VALUES ('Strzelce');
INSERT INTO City(name) VALUES ('Bijie');
INSERT INTO City(name) VALUES ('Araxá');
INSERT INTO City(name) VALUES ('Cova Figueira');
INSERT INTO City(name) VALUES ('Strathmore');
INSERT INTO City(name) VALUES ('San Jacinto');
INSERT INTO City(name) VALUES ('Dzhayrakh');
INSERT INTO City(name) VALUES ('Narach');
INSERT INTO City(name) VALUES ('Kåge');
INSERT INTO City(name) VALUES ('Villa Yapacaní');
INSERT INTO City(name) VALUES ('Taozixi');
INSERT INTO City(name) VALUES ('Hlybokaye');
INSERT INTO City(name) VALUES ('Nantang');
INSERT INTO City(name) VALUES ('Pampa del Infierno');
INSERT INTO City(name) VALUES ('Jinshan');
INSERT INTO City(name) VALUES ('Wiesbaden');
INSERT INTO City(name) VALUES ('Kampungbaru');
INSERT INTO City(name) VALUES ('Lihu');
INSERT INTO City(name) VALUES ('Zhulebino');
INSERT INTO City(name) VALUES ('Koani Ndogo');
INSERT INTO City(name) VALUES ('San Simón');
INSERT INTO City(name) VALUES ('Baiyinnuole');
INSERT INTO City(name) VALUES ('N’dalatando');
INSERT INTO City(name) VALUES ('Taiobeiras');
INSERT INTO City(name) VALUES ('Vuzenica');
INSERT INTO City(name) VALUES ('Yancheng');
INSERT INTO City(name) VALUES ('Ognevka');
INSERT INTO City(name) VALUES ('Zalaegerszeg');
INSERT INTO City(name) VALUES ('Yakovlevo');
INSERT INTO City(name) VALUES ('Ijebu-Ife');
INSERT INTO City(name) VALUES ('Or Yehuda');
INSERT INTO City(name) VALUES ('Aravissós');
INSERT INTO City(name) VALUES ('Guanghai');
INSERT INTO City(name) VALUES ('Bang Pa-in');
INSERT INTO City(name) VALUES ('Cholpon-Ata');
INSERT INTO City(name) VALUES ('Dobšice');
INSERT INTO City(name) VALUES ('Zaragoza');
INSERT INTO City(name) VALUES ('As Samawah');
INSERT INTO City(name) VALUES ('Torre de Moncorvo');
INSERT INTO City(name) VALUES ('Kedungtaman');
INSERT INTO City(name) VALUES ('Tongxing');
INSERT INTO City(name) VALUES ('San Julian');
INSERT INTO City(name) VALUES ('Berestechko');
INSERT INTO City(name) VALUES ('Kuala Lumpur');
INSERT INTO City(name) VALUES ('Hikone');
INSERT INTO City(name) VALUES ('Zhongchao');
INSERT INTO City(name) VALUES ('Shi’ao');
INSERT INTO City(name) VALUES ('Englewood');
INSERT INTO City(name) VALUES ('Niš');
INSERT INTO City(name) VALUES ('Osieck');
INSERT INTO City(name) VALUES ('Benhong');
INSERT INTO City(name) VALUES ('Debar');
INSERT INTO City(name) VALUES ('Tubalan');
INSERT INTO City(name) VALUES ('Fry?ovice');
INSERT INTO City(name) VALUES ('Kozhva');
INSERT INTO City(name) VALUES ('Zalesnoye');
INSERT INTO City(name) VALUES ('Aktau');
INSERT INTO City(name) VALUES ('Rio Claro');
INSERT INTO City(name) VALUES ('Suzano');
INSERT INTO City(name) VALUES ('San Agustín');
INSERT INTO City(name) VALUES ('Asopós');
INSERT INTO City(name) VALUES ('Bardaï');
INSERT INTO City(name) VALUES ('Yurimaguas');
INSERT INTO City(name) VALUES ('Kudus');
INSERT INTO City(name) VALUES ('George Hill');
INSERT INTO City(name) VALUES ('Genzi');
INSERT INTO City(name) VALUES ('Naranjito');
INSERT INTO City(name) VALUES ('Langkapcaang Hilir');
INSERT INTO City(name) VALUES ('Volokonovka');
INSERT INTO City(name) VALUES ('Guaratinguetá');
INSERT INTO City(name) VALUES ('Modosinal');
INSERT INTO City(name) VALUES ('Nueva Cajamarca');
INSERT INTO City(name) VALUES ('Riihimäki');
INSERT INTO City(name) VALUES ('Tonggakjati');
INSERT INTO City(name) VALUES ('Kurihashi');
INSERT INTO City(name) VALUES ('Cachadinha');
INSERT INTO City(name) VALUES ('Shaoha');
INSERT INTO City(name) VALUES ('Irará');
INSERT INTO City(name) VALUES ('Khorostkiv');
INSERT INTO City(name) VALUES ('Timeng');
INSERT INTO City(name) VALUES ('Moshiyi');
INSERT INTO City(name) VALUES ('Dakoutun');
INSERT INTO City(name) VALUES ('Knivsta');
INSERT INTO City(name) VALUES ('Bergen op Zoom');
INSERT INTO City(name) VALUES ('Las Vegas Santa Bar');
INSERT INTO City(name) VALUES ('Douala');
INSERT INTO City(name) VALUES ('Huangzhuang');
INSERT INTO City(name) VALUES ('Hengdian');
INSERT INTO City(name) VALUES ('Zandak');
INSERT INTO City(name) VALUES ('Sémbé');
INSERT INTO City(name) VALUES ('Bagalangit');
INSERT INTO City(name) VALUES ('Vrbovec');
INSERT INTO City(name) VALUES ('Guanting');
INSERT INTO City(name) VALUES ('Dortmund');
INSERT INTO City(name) VALUES ('Kuala Lumpur');
INSERT INTO City(name) VALUES ('Ouégoa');
INSERT INTO City(name) VALUES ('Dongpu');
INSERT INTO City(name) VALUES ('Sadowie');
INSERT INTO City(name) VALUES ('Bourges');
INSERT INTO City(name) VALUES ('Billa');
INSERT INTO City(name) VALUES ('Paratunka');
INSERT INTO City(name) VALUES ('Brak');
INSERT INTO City(name) VALUES ('Mingora');
INSERT INTO City(name) VALUES ('Bunigeulis');
INSERT INTO City(name) VALUES ('Olsztynek');
INSERT INTO City(name) VALUES ('Mengeš');
INSERT INTO City(name) VALUES ('Vila Ribeiro');
INSERT INTO City(name) VALUES ('Kathu');
INSERT INTO City(name) VALUES ('Kyriáki');
INSERT INTO City(name) VALUES ('Xuetian');
INSERT INTO City(name) VALUES ('Barayong');
INSERT INTO City(name) VALUES ('Aucallama');
INSERT INTO City(name) VALUES ('Khao Kho');
INSERT INTO City(name) VALUES ('Cervantes');
INSERT INTO City(name) VALUES ('Karanglincak');
INSERT INTO City(name) VALUES ('Empangeni');
INSERT INTO City(name) VALUES ('Engenheiro Beltrão');
INSERT INTO City(name) VALUES ('Santana');
INSERT INTO City(name) VALUES ('Orsay');
INSERT INTO City(name) VALUES ('Bogandinskiy');
INSERT INTO City(name) VALUES ('Wojcieszków');
INSERT INTO City(name) VALUES ('Radenka');
INSERT INTO City(name) VALUES ('Talnakh');
INSERT INTO City(name) VALUES ('Busungbiu');
INSERT INTO City(name) VALUES ('Damiku');
INSERT INTO City(name) VALUES ('Amiens');
INSERT INTO City(name) VALUES ('Tsiroanomandidy');
INSERT INTO City(name) VALUES ('Longsheng');
INSERT INTO City(name) VALUES ('Ivatsevichy');
INSERT INTO City(name) VALUES ('Rudong');
INSERT INTO City(name) VALUES ('Yesan');
INSERT INTO City(name) VALUES ('Hezhang');
INSERT INTO City(name) VALUES ('Meijiahe');
INSERT INTO City(name) VALUES ('Verkhniy Baskunchak');
INSERT INTO City(name) VALUES ('Kuanheum');
INSERT INTO City(name) VALUES ('Louisville');
INSERT INTO City(name) VALUES ('Titay');
INSERT INTO City(name) VALUES ('Homa Bay');
INSERT INTO City(name) VALUES ('Shuidun');
INSERT INTO City(name) VALUES ('?????????');
INSERT INTO City(name) VALUES ('Santiago Atitlán');
INSERT INTO City(name) VALUES ('Jinshan');
INSERT INTO City(name) VALUES ('Öndörhoshuu');
INSERT INTO City(name) VALUES ('Dayton');
INSERT INTO City(name) VALUES ('Zhongling');
INSERT INTO City(name) VALUES ('Duzhenwan');
INSERT INTO City(name) VALUES ('Jingxin');
INSERT INTO City(name) VALUES ('Lixiqiao');
INSERT INTO City(name) VALUES ('Panev?žys');
INSERT INTO City(name) VALUES ('Krasnapollye');
INSERT INTO City(name) VALUES ('Taoyuan');
INSERT INTO City(name) VALUES ('Canhas');
INSERT INTO City(name) VALUES ('Suruhwadang');
INSERT INTO City(name) VALUES ('Irirum');
INSERT INTO City(name) VALUES ('Novoshakhtinskiy');
INSERT INTO City(name) VALUES ('Guri i Zi');
INSERT INTO City(name) VALUES ('Dangmu');
INSERT INTO City(name) VALUES ('Mougins');
INSERT INTO City(name) VALUES ('Jardín América');
INSERT INTO City(name) VALUES ('Youhua');
INSERT INTO City(name) VALUES ('Tanjungpecinan Utara');
INSERT INTO City(name) VALUES ('Youludu Sibage');
INSERT INTO City(name) VALUES ('Jadho');
INSERT INTO City(name) VALUES ('Kuishan');
INSERT INTO City(name) VALUES ('Yaransk');
INSERT INTO City(name) VALUES ('Chikan');
INSERT INTO City(name) VALUES ('Bokhan');
INSERT INTO City(name) VALUES ('Tamra');
INSERT INTO City(name) VALUES ('Cinco Saltos');
INSERT INTO City(name) VALUES ('Youfang');
INSERT INTO City(name) VALUES ('Koilás');
INSERT INTO City(name) VALUES ('Nato');
INSERT INTO City(name) VALUES ('Zamboanguita');
INSERT INTO City(name) VALUES ('Brze?nica');
INSERT INTO City(name) VALUES ('Regnów');
INSERT INTO City(name) VALUES ('Jiantang');
INSERT INTO City(name) VALUES ('Pingkai');
INSERT INTO City(name) VALUES ('Taluksangay');
INSERT INTO City(name) VALUES ('Xiaoshiqiao');
INSERT INTO City(name) VALUES ('Floresta');
INSERT INTO City(name) VALUES ('Takub');
INSERT INTO City(name) VALUES ('Montego Bay');
INSERT INTO City(name) VALUES ('Hobonio');
INSERT INTO City(name) VALUES ('San Marcos');
INSERT INTO City(name) VALUES ('Lumbatan');
INSERT INTO City(name) VALUES ('Säter');
INSERT INTO City(name) VALUES ('Ngeni');
INSERT INTO City(name) VALUES ('Lagyná');
INSERT INTO City(name) VALUES ('Gavea');
INSERT INTO City(name) VALUES ('Baiguo');
INSERT INTO City(name) VALUES ('Calde');
INSERT INTO City(name) VALUES ('Indianapolis');
INSERT INTO City(name) VALUES ('Bus’k');
INSERT INTO City(name) VALUES ('Albuquerque');
INSERT INTO City(name) VALUES ('Lagangilang');
INSERT INTO City(name) VALUES ('Tubel');
INSERT INTO City(name) VALUES ('San José de Jáchal');
INSERT INTO City(name) VALUES ('Pilar');
INSERT INTO City(name) VALUES ('Charleville-Mézières');
INSERT INTO City(name) VALUES ('Heyin');
INSERT INTO City(name) VALUES ('Xinsheng');
INSERT INTO City(name) VALUES ('Lypova Dolyna');
INSERT INTO City(name) VALUES ('Casal Galego');
INSERT INTO City(name) VALUES ('Angono');
INSERT INTO City(name) VALUES ('Ágios Matthaíos');
INSERT INTO City(name) VALUES ('Mýki');
INSERT INTO City(name) VALUES ('Ketapang');
INSERT INTO City(name) VALUES ('Mendenrejo');
INSERT INTO City(name) VALUES ('Vinsady');
INSERT INTO City(name) VALUES ('Sukodono');
INSERT INTO City(name) VALUES ('Jämsänkoski');
INSERT INTO City(name) VALUES ('Ochakovo-Matveyevskoye');
INSERT INTO City(name) VALUES ('Palermo');
INSERT INTO City(name) VALUES ('Dois Córregos');
INSERT INTO City(name) VALUES ('Sarv?b?d');
INSERT INTO City(name) VALUES ('Al Ma?allah al Kubrá');
INSERT INTO City(name) VALUES ('Puunage');
INSERT INTO City(name) VALUES ('J?ma');
INSERT INTO City(name) VALUES ('Oslo');
INSERT INTO City(name) VALUES ('Santo André');
INSERT INTO City(name) VALUES ('Kuafeu');
INSERT INTO City(name) VALUES ('Shiyaogou');
INSERT INTO City(name) VALUES ('Roanne');
INSERT INTO City(name) VALUES ('Beitan');
INSERT INTO City(name) VALUES ('Estelí');
INSERT INTO City(name) VALUES ('Svetlyy');
INSERT INTO City(name) VALUES ('Krasnokumskoye');
INSERT INTO City(name) VALUES ('?ešinovo');
INSERT INTO City(name) VALUES ('Champagnole');
INSERT INTO City(name) VALUES ('Comrat');
INSERT INTO City(name) VALUES ('Aurora');
INSERT INTO City(name) VALUES ('Barabedang');
INSERT INTO City(name) VALUES ('Biñan');
INSERT INTO City(name) VALUES ('Daireaux');
INSERT INTO City(name) VALUES ('Tulung');
INSERT INTO City(name) VALUES ('Ialibu');
INSERT INTO City(name) VALUES ('Santo Amaro');
INSERT INTO City(name) VALUES ('Sofifi');
INSERT INTO City(name) VALUES ('Dabai');
INSERT INTO City(name) VALUES ('Çalxanqala');
INSERT INTO City(name) VALUES ('Y?nan-?p');
INSERT INTO City(name) VALUES ('San Antonio Ilotenango');
INSERT INTO City(name) VALUES ('Laban');
INSERT INTO City(name) VALUES ('Tsimasham');
INSERT INTO City(name) VALUES ('Golubinci');
INSERT INTO City(name) VALUES ('Mullsjö');
INSERT INTO City(name) VALUES ('Grenoble');
INSERT INTO City(name) VALUES ('Wangshi');
INSERT INTO City(name) VALUES ('Boyu');
INSERT INTO City(name) VALUES ('Willemstad');
INSERT INTO City(name) VALUES ('Mitzpe Ramon');
INSERT INTO City(name) VALUES ('Kun?ice pod Ond?ejníkem');
INSERT INTO City(name) VALUES ('Mbanga');
INSERT INTO City(name) VALUES ('Loma Bonita');
INSERT INTO City(name) VALUES ('Tongjing');
INSERT INTO City(name) VALUES ('Vychegodskiy');
INSERT INTO City(name) VALUES ('Fanhu');
INSERT INTO City(name) VALUES ('Qal‘ah-ye Kuhnah');
INSERT INTO City(name) VALUES ('Pershotravneve');
INSERT INTO City(name) VALUES ('Samut Prakan');
INSERT INTO City(name) VALUES ('Ayapel');
INSERT INTO City(name) VALUES ('‘Abas?n al Kab?rah');
INSERT INTO City(name) VALUES ('Temara');
INSERT INTO City(name) VALUES ('Sumurber');
INSERT INTO City(name) VALUES ('Banjar Kampungbugis');
INSERT INTO City(name) VALUES ('Gaurnadi');
INSERT INTO City(name) VALUES ('Kablukan');
INSERT INTO City(name) VALUES ('Barentu');
INSERT INTO City(name) VALUES ('Wahawaha');
INSERT INTO City(name) VALUES ('Masaran');
INSERT INTO City(name) VALUES ('Thap Khlo');
INSERT INTO City(name) VALUES ('Balete');
INSERT INTO City(name) VALUES ('Presidente Médici');
INSERT INTO City(name) VALUES ('Dawan');
INSERT INTO City(name) VALUES ('Nantes');
INSERT INTO City(name) VALUES ('Yanglin');
INSERT INTO City(name) VALUES ('Dafundo');
INSERT INTO City(name) VALUES ('Zhangye');
INSERT INTO City(name) VALUES ('Lagunas');
INSERT INTO City(name) VALUES ('Tonantins');
INSERT INTO City(name) VALUES ('Buenavista');
INSERT INTO City(name) VALUES ('Sudimara');
INSERT INTO City(name) VALUES ('Siemi?tkowo');
INSERT INTO City(name) VALUES ('Buçimas');
INSERT INTO City(name) VALUES ('Na Yong');
INSERT INTO City(name) VALUES ('Grahamstown');
INSERT INTO City(name) VALUES ('Cedar Rapids');
INSERT INTO City(name) VALUES ('Shikhazany');
INSERT INTO City(name) VALUES ('Degeberga');
INSERT INTO City(name) VALUES ('Zamora');
INSERT INTO City(name) VALUES ('Sinamar');
INSERT INTO City(name) VALUES ('Th? Tr?n Pác Mi?u');
INSERT INTO City(name) VALUES ('Tianzishan');
INSERT INTO City(name) VALUES ('Nong Khai');
INSERT INTO City(name) VALUES ('Gia Ngh?a');
INSERT INTO City(name) VALUES ('Vale de Figueira');
INSERT INTO City(name) VALUES ('Jackson');
INSERT INTO City(name) VALUES ('Kluczbork');
INSERT INTO City(name) VALUES ('Xianlin');
INSERT INTO City(name) VALUES ('Baiguan');
INSERT INTO City(name) VALUES ('Tsybulevka');
INSERT INTO City(name) VALUES ('Las Vegas');
INSERT INTO City(name) VALUES ('Vareiá');
INSERT INTO City(name) VALUES ('Semamung');
INSERT INTO City(name) VALUES ('Longquan');
INSERT INTO City(name) VALUES ('Slavs’ke');
INSERT INTO City(name) VALUES ('Semirara');
INSERT INTO City(name) VALUES ('Chabany');
INSERT INTO City(name) VALUES ('Zimmi');
INSERT INTO City(name) VALUES ('Gabès');
INSERT INTO City(name) VALUES ('Qikeshu');
INSERT INTO City(name) VALUES ('Winangun');
INSERT INTO City(name) VALUES ('Columbus');
INSERT INTO City(name) VALUES ('Sokolov');
INSERT INTO City(name) VALUES ('Changsha');
INSERT INTO City(name) VALUES ('Bebedouro');
INSERT INTO City(name) VALUES ('Kedawung');
INSERT INTO City(name) VALUES ('Panev?žys');
INSERT INTO City(name) VALUES ('Kutorejo');
INSERT INTO City(name) VALUES ('Batas Barat');
INSERT INTO City(name) VALUES ('Viña del Mar');
INSERT INTO City(name) VALUES ('Jintao');
INSERT INTO City(name) VALUES ('Oliveira de Baixo');
INSERT INTO City(name) VALUES ('????????');
INSERT INTO City(name) VALUES ('Souran');
INSERT INTO City(name) VALUES ('Massy');
INSERT INTO City(name) VALUES ('Gon?b?d');
INSERT INTO City(name) VALUES ('Domanín');
INSERT INTO City(name) VALUES ('Philadelphia');
INSERT INTO City(name) VALUES ('Dawuhanmangli');
INSERT INTO City(name) VALUES ('Mikhaylovka');
INSERT INTO City(name) VALUES ('Buluangan');
INSERT INTO City(name) VALUES ('Le Grand-Quevilly');
INSERT INTO City(name) VALUES ('Menggala');
INSERT INTO City(name) VALUES ('Esmoriz');
INSERT INTO City(name) VALUES ('Pingyang');
INSERT INTO City(name) VALUES ('Powassan');
INSERT INTO City(name) VALUES ('Mirotice');
INSERT INTO City(name) VALUES ('Van Nuys');
INSERT INTO City(name) VALUES ('Roxas');
INSERT INTO City(name) VALUES ('Cherëmukhovo');
INSERT INTO City(name) VALUES ('Stockholm');
INSERT INTO City(name) VALUES ('Umm Ruwaba');
INSERT INTO City(name) VALUES ('Thatta');
INSERT INTO City(name) VALUES ('Tomas');
INSERT INTO City(name) VALUES ('Kaduengang');
INSERT INTO City(name) VALUES ('Estância');
INSERT INTO City(name) VALUES ('Tawaran');
INSERT INTO City(name) VALUES ('Wangqingtuo');
INSERT INTO City(name) VALUES ('Huacrachuco');
INSERT INTO City(name) VALUES ('San Sebastian');
INSERT INTO City(name) VALUES ('Insua');
INSERT INTO City(name) VALUES ('Maiorca');
INSERT INTO City(name) VALUES ('Kota Kinabalu');
INSERT INTO City(name) VALUES ('Nancun');
INSERT INTO City(name) VALUES ('Salamwates');
INSERT INTO City(name) VALUES ('Yanshou');
INSERT INTO City(name) VALUES ('El Vigía');
INSERT INTO City(name) VALUES ('Garanhuns');
INSERT INTO City(name) VALUES ('Covão da Carvalha');
INSERT INTO City(name) VALUES ('Isla Pucú');
INSERT INTO City(name) VALUES ('Chitagá');
INSERT INTO City(name) VALUES ('Cuilco');
INSERT INTO City(name) VALUES ('Cergy-Pontoise');
INSERT INTO City(name) VALUES ('Kaliska');
INSERT INTO City(name) VALUES ('Úšt?k');
INSERT INTO City(name) VALUES ('Podgorenskiy');
INSERT INTO City(name) VALUES ('Nanzhihui');
INSERT INTO City(name) VALUES ('Letuyi');
INSERT INTO City(name) VALUES ('Pingqiao');
INSERT INTO City(name) VALUES ('Portela');
INSERT INTO City(name) VALUES ('Ciulu');
INSERT INTO City(name) VALUES ('Mauloo');
INSERT INTO City(name) VALUES ('Pelym');
INSERT INTO City(name) VALUES ('Limín Khersonísou');
INSERT INTO City(name) VALUES ('Jinzao');
INSERT INTO City(name) VALUES ('Pangradin Satu');
INSERT INTO City(name) VALUES ('Kaem');
INSERT INTO City(name) VALUES ('Sadovo');
INSERT INTO City(name) VALUES ('Osvaldo Cruz');
INSERT INTO City(name) VALUES ('Santa Rita');
INSERT INTO City(name) VALUES ('Mtambile');
INSERT INTO City(name) VALUES ('Maj?z al B?b');
INSERT INTO City(name) VALUES ('Alivéri');
INSERT INTO City(name) VALUES ('Cruz');
INSERT INTO City(name) VALUES ('Shanling');
INSERT INTO City(name) VALUES ('Bobigny');
INSERT INTO City(name) VALUES ('Denglong');
INSERT INTO City(name) VALUES ('Awka');
INSERT INTO City(name) VALUES ('Saltpond');
INSERT INTO City(name) VALUES ('Huolongping');
INSERT INTO City(name) VALUES ('Palcza');
INSERT INTO City(name) VALUES ('Santa Rita');
INSERT INTO City(name) VALUES ('Torre');
INSERT INTO City(name) VALUES ('Log');
INSERT INTO City(name) VALUES ('Viçosa do Ceará');
INSERT INTO City(name) VALUES ('Terezín');
INSERT INTO City(name) VALUES ('Shun’ga');
INSERT INTO City(name) VALUES ('Xiaozhen');
INSERT INTO City(name) VALUES ('Batawa');
INSERT INTO City(name) VALUES ('Carrasqueira');
INSERT INTO City(name) VALUES ('Hulan');
INSERT INTO City(name) VALUES ('Sungailiat');
INSERT INTO City(name) VALUES ('Coja');
INSERT INTO City(name) VALUES ('Fergana');
INSERT INTO City(name) VALUES ('Mendeleyevsk');
INSERT INTO City(name) VALUES ('Río Cauto');
INSERT INTO City(name) VALUES ('Ibaiti');
INSERT INTO City(name) VALUES ('Privodino');
INSERT INTO City(name) VALUES ('Xiangyang');
INSERT INTO City(name) VALUES ('Altkirch');
INSERT INTO City(name) VALUES ('Kronoby');
INSERT INTO City(name) VALUES ('Kalibunder');
INSERT INTO City(name) VALUES ('Zhanggongmiao');
INSERT INTO City(name) VALUES ('Suzhou');
INSERT INTO City(name) VALUES ('Goundi');
INSERT INTO City(name) VALUES ('Cova Figueira');
INSERT INTO City(name) VALUES ('Nombre de Jesús');
INSERT INTO City(name) VALUES ('Cholet');
INSERT INTO City(name) VALUES ('Amagi');
INSERT INTO City(name) VALUES ('Xintian');
INSERT INTO City(name) VALUES ('Huanglong');
INSERT INTO City(name) VALUES ('La Chapelle-sur-Erdre');
INSERT INTO City(name) VALUES ('Erling');
INSERT INTO City(name) VALUES ('Zhenyuan');
INSERT INTO City(name) VALUES ('Liulin');
INSERT INTO City(name) VALUES ('Kimito');
INSERT INTO City(name) VALUES ('Atuntaqui');
INSERT INTO City(name) VALUES ('Shinyanga');
INSERT INTO City(name) VALUES ('Rimba Sekampung');
INSERT INTO City(name) VALUES ('Jiaxian Chengguanzhen');
INSERT INTO City(name) VALUES ('Chakari');
INSERT INTO City(name) VALUES ('Kalde Panga');
INSERT INTO City(name) VALUES ('Damascus');
INSERT INTO City(name) VALUES ('Yingta');
INSERT INTO City(name) VALUES ('Tandag');
INSERT INTO City(name) VALUES ('Hele');
INSERT INTO City(name) VALUES ('Sinargalih');
INSERT INTO City(name) VALUES ('Blois');
INSERT INTO City(name) VALUES ('Nurlat');
INSERT INTO City(name) VALUES ('Saint-Denis');
INSERT INTO City(name) VALUES ('Pocohuanca');
INSERT INTO City(name) VALUES ('Lloque');
INSERT INTO City(name) VALUES ('Pyatigorsk');
INSERT INTO City(name) VALUES ('Lidingö');
INSERT INTO City(name) VALUES ('Hallstavik');
INSERT INTO City(name) VALUES ('Maraã');
INSERT INTO City(name) VALUES ('‘Af?f');
INSERT INTO City(name) VALUES ('Borucin');
INSERT INTO City(name) VALUES ('Castelo de Vide');
INSERT INTO City(name) VALUES ('Mâcon');
INSERT INTO City(name) VALUES ('Onomichi');
INSERT INTO City(name) VALUES ('Radzanów');
INSERT INTO City(name) VALUES ('Detroit');
INSERT INTO City(name) VALUES ('Celestynów');
INSERT INTO City(name) VALUES ('Barrie');
INSERT INTO City(name) VALUES ('Darkovice');
INSERT INTO City(name) VALUES ('Horní Lide?');
INSERT INTO City(name) VALUES ('Banjar Jabejero');
INSERT INTO City(name) VALUES ('Buliran');
INSERT INTO City(name) VALUES ('Hekinan');
INSERT INTO City(name) VALUES ('Jingcheng');
INSERT INTO City(name) VALUES ('Åtvidaberg');
INSERT INTO City(name) VALUES ('Charlesland');
INSERT INTO City(name) VALUES ('Verkhniye Kigi');
INSERT INTO City(name) VALUES ('Morrinhos');
INSERT INTO City(name) VALUES ('Shahe');
INSERT INTO City(name) VALUES ('Poteran');
INSERT INTO City(name) VALUES ('Marneuli');
INSERT INTO City(name) VALUES ('Hòa Bình');
INSERT INTO City(name) VALUES ('Mueang Nonthaburi');
INSERT INTO City(name) VALUES ('Hiratach?');
INSERT INTO City(name) VALUES ('Pirg');
INSERT INTO City(name) VALUES ('Tamel');
INSERT INTO City(name) VALUES ('Lumbac');
INSERT INTO City(name) VALUES ('Khan??ir');
INSERT INTO City(name) VALUES ('São Lourenço do Sul');
INSERT INTO City(name) VALUES ('Casilda');
INSERT INTO City(name) VALUES ('Oesapa');
INSERT INTO City(name) VALUES ('Diez de Octubre');
INSERT INTO City(name) VALUES ('Bazz?ryah');
INSERT INTO City(name) VALUES ('Cantaura');
INSERT INTO City(name) VALUES ('Triesenberg');
INSERT INTO City(name) VALUES ('Garden Grove');
INSERT INTO City(name) VALUES ('Shanhe');
INSERT INTO City(name) VALUES ('Sagae');
INSERT INTO City(name) VALUES ('Kukuna');
INSERT INTO City(name) VALUES ('København');
INSERT INTO City(name) VALUES ('Soraya');
INSERT INTO City(name) VALUES ('Quinta da Torre');
INSERT INTO City(name) VALUES ('Ambovombe');
INSERT INTO City(name) VALUES ('Lanús');
INSERT INTO City(name) VALUES ('Suso');
INSERT INTO City(name) VALUES ('Obryte');
INSERT INTO City(name) VALUES ('Chenqing');
INSERT INTO City(name) VALUES ('Gbarnga');
INSERT INTO City(name) VALUES ('Shigu');
INSERT INTO City(name) VALUES ('Taiping');
INSERT INTO City(name) VALUES ('Susiec');
INSERT INTO City(name) VALUES ('Chengzhai');
INSERT INTO City(name) VALUES ('Bijeli');
INSERT INTO City(name) VALUES ('Ostrožská Nová Ves');
INSERT INTO City(name) VALUES ('Inanwatan');
INSERT INTO City(name) VALUES ('Be?ej');
INSERT INTO City(name) VALUES ('Mopti');
INSERT INTO City(name) VALUES ('Puerto Madryn');
INSERT INTO City(name) VALUES ('Maroua');
INSERT INTO City(name) VALUES ('Budapest');
INSERT INTO City(name) VALUES ('Sáchica');
INSERT INTO City(name) VALUES ('Daoxu');
INSERT INTO City(name) VALUES ('Nice');
INSERT INTO City(name) VALUES ('Ongkharak');
INSERT INTO City(name) VALUES ('Bulakan');
INSERT INTO City(name) VALUES ('Linzi');
INSERT INTO City(name) VALUES ('Ormož');
INSERT INTO City(name) VALUES ('Uychi');
INSERT INTO City(name) VALUES ('Voskopojë');
INSERT INTO City(name) VALUES ('Kudang');
INSERT INTO City(name) VALUES ('Agnibilékrou');
INSERT INTO City(name) VALUES ('Angers');
INSERT INTO City(name) VALUES ('Malummaduri');
INSERT INTO City(name) VALUES ('Jiangkou');
INSERT INTO City(name) VALUES ('Mariara');
INSERT INTO City(name) VALUES ('Malambo');
INSERT INTO City(name) VALUES ('Lubenec');
INSERT INTO City(name) VALUES ('Dodola');
INSERT INTO City(name) VALUES ('Sandaohezi');
INSERT INTO City(name) VALUES ('Vila Real de Santo António');
INSERT INTO City(name) VALUES ('Zhuravka');
INSERT INTO City(name) VALUES ('Söderhamn');
INSERT INTO City(name) VALUES ('Penha');
INSERT INTO City(name) VALUES ('Anyama');
INSERT INTO City(name) VALUES ('Aiguo');
INSERT INTO City(name) VALUES ('Klavdiyevo-Tarasove');
INSERT INTO City(name) VALUES ('Bitin');
INSERT INTO City(name) VALUES ('‘Abas?n al Kab?rah');
INSERT INTO City(name) VALUES ('Périgny');
INSERT INTO City(name) VALUES ('Milín');
INSERT INTO City(name) VALUES ('Darong');
INSERT INTO City(name) VALUES ('Cikulahan');
INSERT INTO City(name) VALUES ('Kota Bharu');
INSERT INTO City(name) VALUES ('L''Épiphanie');
INSERT INTO City(name) VALUES ('Guangang');
INSERT INTO City(name) VALUES ('Bubullimë');
INSERT INTO City(name) VALUES ('Shilong');
INSERT INTO City(name) VALUES ('San Sebastián de Yalí');
INSERT INTO City(name) VALUES ('Boca Chica');
INSERT INTO City(name) VALUES ('Pinggang');
INSERT INTO City(name) VALUES ('Boa Vista');
INSERT INTO City(name) VALUES ('Lindome');
INSERT INTO City(name) VALUES ('Fovissste');
INSERT INTO City(name) VALUES ('Nakhon Nayok');
INSERT INTO City(name) VALUES ('Sausa');
INSERT INTO City(name) VALUES ('Jedlová');
INSERT INTO City(name) VALUES ('Al ‘?qir');
INSERT INTO City(name) VALUES ('Khlong Yai');
INSERT INTO City(name) VALUES ('Czy?owice');
INSERT INTO City(name) VALUES ('Elimäki');
INSERT INTO City(name) VALUES ('Hongyuan');
INSERT INTO City(name) VALUES ('Tílisos');
INSERT INTO City(name) VALUES ('Tarariras');
INSERT INTO City(name) VALUES ('Gaopi');
INSERT INTO City(name) VALUES ('Erátyra');
INSERT INTO City(name) VALUES ('Johanneshov');
INSERT INTO City(name) VALUES ('Tikhoretsk');
INSERT INTO City(name) VALUES ('Barrie');
INSERT INTO City(name) VALUES ('Saint-Quentin-en-Yvelines');
INSERT INTO City(name) VALUES ('Sanzhang');
INSERT INTO City(name) VALUES ('Baoli');
INSERT INTO City(name) VALUES ('Santa Marta');
INSERT INTO City(name) VALUES ('Kraljevica');
INSERT INTO City(name) VALUES ('Ishim');
INSERT INTO City(name) VALUES ('Cabadiangan');
INSERT INTO City(name) VALUES ('Zhongshi');
INSERT INTO City(name) VALUES ('Cimahi');
INSERT INTO City(name) VALUES ('Srostki');
INSERT INTO City(name) VALUES ('Zhavoronki');
INSERT INTO City(name) VALUES ('Kaédi');
INSERT INTO City(name) VALUES ('Banjar Kubu');
INSERT INTO City(name) VALUES ('Quinta');
INSERT INTO City(name) VALUES ('Abidjan');
INSERT INTO City(name) VALUES ('Kaolack');
INSERT INTO City(name) VALUES ('Stari Grad');
INSERT INTO City(name) VALUES ('Nangerang');
INSERT INTO City(name) VALUES ('Cúa');
INSERT INTO City(name) VALUES ('Florencia');
INSERT INTO City(name) VALUES ('C?u Gi?y');
INSERT INTO City(name) VALUES ('Xieji');
INSERT INTO City(name) VALUES ('Karangmelok');
INSERT INTO City(name) VALUES ('Baiyashi');
INSERT INTO City(name) VALUES ('Taytayan');
INSERT INTO City(name) VALUES ('Fenghuangdong');
INSERT INTO City(name) VALUES ('Ea T’ling');
INSERT INTO City(name) VALUES ('Nikhom Kham Soi');
INSERT INTO City(name) VALUES ('Chvaletice');
INSERT INTO City(name) VALUES ('Tawun');
INSERT INTO City(name) VALUES ('Asunción');
INSERT INTO City(name) VALUES ('Huochang');
INSERT INTO City(name) VALUES ('Bolinao');
INSERT INTO City(name) VALUES ('??ki');
INSERT INTO City(name) VALUES ('Podgortsy');
INSERT INTO City(name) VALUES ('Kapyl’');
INSERT INTO City(name) VALUES ('Rajapeni');
INSERT INTO City(name) VALUES ('Pereiras');
INSERT INTO City(name) VALUES ('Pyetrykaw');
INSERT INTO City(name) VALUES ('Pucyura');
INSERT INTO City(name) VALUES ('Sandia');
INSERT INTO City(name) VALUES ('La Escondida');
INSERT INTO City(name) VALUES ('Nanterre');
INSERT INTO City(name) VALUES ('Junchuan');
INSERT INTO City(name) VALUES ('Västerås');
INSERT INTO City(name) VALUES ('Al B?j?r');
INSERT INTO City(name) VALUES ('Minian');
INSERT INTO City(name) VALUES ('Air Bangis');
INSERT INTO City(name) VALUES ('Shuiquan');
INSERT INTO City(name) VALUES ('Huangshi');
INSERT INTO City(name) VALUES ('Laotai');
INSERT INTO City(name) VALUES ('Ingå');
INSERT INTO City(name) VALUES ('Kelaniya');
INSERT INTO City(name) VALUES ('Lago da Pedra');
INSERT INTO City(name) VALUES ('Novosineglazovskiy');
INSERT INTO City(name) VALUES ('Pasembon');
INSERT INTO City(name) VALUES ('Krajan Alasdowo');
INSERT INTO City(name) VALUES ('Qingxi');
INSERT INTO City(name) VALUES ('Rebe');
INSERT INTO City(name) VALUES ('Iogach');
INSERT INTO City(name) VALUES ('Usquil');
INSERT INTO City(name) VALUES ('Mufumbwe');
INSERT INTO City(name) VALUES ('Priargunsk');
INSERT INTO City(name) VALUES ('Honglan');
INSERT INTO City(name) VALUES ('Xincheng Chengguanzhen');
INSERT INTO City(name) VALUES ('Din?jpur');
INSERT INTO City(name) VALUES ('Tangguhang');
INSERT INTO City(name) VALUES ('Frakulla e Madhe');
INSERT INTO City(name) VALUES ('Huipinggeng');
INSERT INTO City(name) VALUES ('Yinglong');
INSERT INTO City(name) VALUES ('Quevedo');
INSERT INTO City(name) VALUES ('Renhe');
INSERT INTO City(name) VALUES ('Fréjus');
INSERT INTO City(name) VALUES ('Dlemer');
INSERT INTO City(name) VALUES ('Burgaltay');
INSERT INTO City(name) VALUES ('Mautapaga Bawah');
INSERT INTO City(name) VALUES ('Miami');
INSERT INTO City(name) VALUES ('Nicolas Bravo');
INSERT INTO City(name) VALUES ('Ponte Nova');
INSERT INTO City(name) VALUES ('Malek?n');
INSERT INTO City(name) VALUES ('Watrous');
INSERT INTO City(name) VALUES ('Peruc');
INSERT INTO City(name) VALUES ('Limoges');
INSERT INTO City(name) VALUES ('Huicheng');
INSERT INTO City(name) VALUES ('Limassol');
INSERT INTO City(name) VALUES ('Legrada');
INSERT INTO City(name) VALUES ('Sant Cugat Del Valles');
INSERT INTO City(name) VALUES ('Bol’shaya Setun’');
INSERT INTO City(name) VALUES ('Bender');
INSERT INTO City(name) VALUES ('Idtig');
INSERT INTO City(name) VALUES ('Fengyi');
INSERT INTO City(name) VALUES ('Sypniewo');
INSERT INTO City(name) VALUES ('General Lavalle');
INSERT INTO City(name) VALUES ('Libon');
INSERT INTO City(name) VALUES ('San Francisco');
INSERT INTO City(name) VALUES ('Sigay');
INSERT INTO City(name) VALUES ('Alicante/Alacant');
INSERT INTO City(name) VALUES ('Katagum');
INSERT INTO City(name) VALUES ('Najin');
INSERT INTO City(name) VALUES ('Olocuilta');
INSERT INTO City(name) VALUES ('Chornukhy');
INSERT INTO City(name) VALUES ('Foumban');
INSERT INTO City(name) VALUES ('Yutsa');
INSERT INTO City(name) VALUES ('Bomomani');
INSERT INTO City(name) VALUES ('Liurenba');
INSERT INTO City(name) VALUES ('Mekarsari');
INSERT INTO City(name) VALUES ('Saint Louis');
INSERT INTO City(name) VALUES ('Momanalu');
INSERT INTO City(name) VALUES ('?om?a');
INSERT INTO City(name) VALUES ('Nagornyy');
INSERT INTO City(name) VALUES ('Khon Kaen');
INSERT INTO City(name) VALUES ('Shchigry');
INSERT INTO City(name) VALUES ('Berezanka');
INSERT INTO City(name) VALUES ('Guihulñgan');
INSERT INTO City(name) VALUES ('Sliema');
INSERT INTO City(name) VALUES ('Jiantian');
INSERT INTO City(name) VALUES ('Racine');
INSERT INTO City(name) VALUES ('Isabela');
INSERT INTO City(name) VALUES ('Dongping');
INSERT INTO City(name) VALUES ('Chengdong');
INSERT INTO City(name) VALUES ('Mumen');
INSERT INTO City(name) VALUES ('Askersund');
INSERT INTO City(name) VALUES ('Sanli');
INSERT INTO City(name) VALUES ('Darfield');
INSERT INTO City(name) VALUES ('Kubanskiy');
INSERT INTO City(name) VALUES ('Moerewa');
INSERT INTO City(name) VALUES ('Cankova');
INSERT INTO City(name) VALUES ('Aktau');
INSERT INTO City(name) VALUES ('Soubré');
INSERT INTO City(name) VALUES ('Jutiapa');
INSERT INTO City(name) VALUES ('Perdões');
INSERT INTO City(name) VALUES ('Lo Prado');
INSERT INTO City(name) VALUES ('Caitang');
INSERT INTO City(name) VALUES ('Puerto López');
INSERT INTO City(name) VALUES ('Maz?r-e Shar?f');
INSERT INTO City(name) VALUES ('Chornukhyne');
INSERT INTO City(name) VALUES ('?ervená Voda');
INSERT INTO City(name) VALUES ('Sidamukti');
INSERT INTO City(name) VALUES ('B?ft');
INSERT INTO City(name) VALUES ('Água Preta');
INSERT INTO City(name) VALUES ('Rizal');
INSERT INTO City(name) VALUES ('San Juan Ermita');
INSERT INTO City(name) VALUES ('la Massana');
INSERT INTO City(name) VALUES ('Wonokromo');
INSERT INTO City(name) VALUES ('Sobreira');
INSERT INTO City(name) VALUES ('Silgueiros');
INSERT INTO City(name) VALUES ('Silvares');
INSERT INTO City(name) VALUES ('Knurów');
INSERT INTO City(name) VALUES ('Starobelokurikha');
INSERT INTO City(name) VALUES ('Tonosh?');
INSERT INTO City(name) VALUES ('Itaqui');
INSERT INTO City(name) VALUES ('Tallinn');
INSERT INTO City(name) VALUES ('Jenesano');
INSERT INTO City(name) VALUES ('Slatyne');
INSERT INTO City(name) VALUES ('Wendengying');
INSERT INTO City(name) VALUES ('Shentang');
INSERT INTO City(name) VALUES ('Nekhayevskiy');
INSERT INTO City(name) VALUES ('Tashtagol');
INSERT INTO City(name) VALUES ('Izazi');
INSERT INTO City(name) VALUES ('McKinley');
INSERT INTO City(name) VALUES ('Nyagla');
INSERT INTO City(name) VALUES ('Mólos');
INSERT INTO City(name) VALUES ('Cential');
INSERT INTO City(name) VALUES ('?d?s Zemen');
INSERT INTO City(name) VALUES ('Atyrá');
INSERT INTO City(name) VALUES ('Puerto Colombia');
INSERT INTO City(name) VALUES ('Cibulakan');
INSERT INTO City(name) VALUES ('Noyal-sur-Vilaine');
INSERT INTO City(name) VALUES ('Palma De Mallorca');
INSERT INTO City(name) VALUES ('Tena');
INSERT INTO City(name) VALUES ('Ayabe');
INSERT INTO City(name) VALUES ('Íasmos');
INSERT INTO City(name) VALUES ('Zhoutian');
INSERT INTO City(name) VALUES ('Sai’erlong Xiang');
INSERT INTO City(name) VALUES ('Yanghuxiang');
INSERT INTO City(name) VALUES ('Fria');
INSERT INTO City(name) VALUES ('Bom Despacho');
INSERT INTO City(name) VALUES ('Ingarö');
INSERT INTO City(name) VALUES ('Q?dirpur R?n');
INSERT INTO City(name) VALUES ('Toledo');
INSERT INTO City(name) VALUES ('Mílos');
INSERT INTO City(name) VALUES ('Borås');
INSERT INTO City(name) VALUES ('Mikulášovice');
INSERT INTO City(name) VALUES ('Bojongsari');
INSERT INTO City(name) VALUES ('Singajaya');
INSERT INTO City(name) VALUES ('Amiens');
INSERT INTO City(name) VALUES ('Kuala Lumpur');
INSERT INTO City(name) VALUES ('Valladolid');
INSERT INTO City(name) VALUES ('Sindanghayu');
INSERT INTO City(name) VALUES ('Adiaké');
INSERT INTO City(name) VALUES ('Baiyang');
INSERT INTO City(name) VALUES ('Yungaisi');
INSERT INTO City(name) VALUES ('Sembungan Kidul');
INSERT INTO City(name) VALUES ('L-Iklin');
INSERT INTO City(name) VALUES ('Tarikolot');
INSERT INTO City(name) VALUES ('Apiaí');
INSERT INTO City(name) VALUES ('Progreso');
INSERT INTO City(name) VALUES ('Kadusirung Hilir');
INSERT INTO City(name) VALUES ('Toukh');
INSERT INTO City(name) VALUES ('Weiting');
INSERT INTO City(name) VALUES ('Escola');
INSERT INTO City(name) VALUES ('Colorado Springs');
INSERT INTO City(name) VALUES ('Kota Kinabalu');
INSERT INTO City(name) VALUES ('Sobreira');
INSERT INTO City(name) VALUES ('Asahikawa');
INSERT INTO City(name) VALUES ('Fuyang');
INSERT INTO City(name) VALUES ('Luga');
INSERT INTO City(name) VALUES ('Utm?nzai');
INSERT INTO City(name) VALUES ('Tugdan');
INSERT INTO City(name) VALUES ('Pohrebyshche');
INSERT INTO City(name) VALUES ('Kwaluseni');
INSERT INTO City(name) VALUES ('Handan');
INSERT INTO City(name) VALUES ('Ljungby');
INSERT INTO City(name) VALUES ('Maromme');
INSERT INTO City(name) VALUES ('Soca');
INSERT INTO City(name) VALUES ('Mingoyo');
INSERT INTO City(name) VALUES ('Khasavyurt');
INSERT INTO City(name) VALUES ('Kishkenekol’');
INSERT INTO City(name) VALUES ('Shibi');
INSERT INTO City(name) VALUES ('Madimba');
INSERT INTO City(name) VALUES ('Yanggan');
INSERT INTO City(name) VALUES ('Borås');
INSERT INTO City(name) VALUES ('Hutang');
INSERT INTO City(name) VALUES ('Vazhiny');
INSERT INTO City(name) VALUES ('Penebel');
INSERT INTO City(name) VALUES ('Carson City');
INSERT INTO City(name) VALUES ('Mekarsari');
INSERT INTO City(name) VALUES ('Bunisari');
INSERT INTO City(name) VALUES ('Stepanivka');
INSERT INTO City(name) VALUES ('Kampunglistrik');
INSERT INTO City(name) VALUES ('Wichian Buri');
INSERT INTO City(name) VALUES ('San Agustín Acasaguastlán');
INSERT INTO City(name) VALUES ('Tal?');
INSERT INTO City(name) VALUES ('Linjiang');
INSERT INTO City(name) VALUES ('Energodar');
INSERT INTO City(name) VALUES ('Gracias');
INSERT INTO City(name) VALUES ('Luau');
INSERT INTO City(name) VALUES ('Józefów');
INSERT INTO City(name) VALUES ('Pokotylivka');
INSERT INTO City(name) VALUES ('Xinmen');
INSERT INTO City(name) VALUES ('Anjirmuara');
INSERT INTO City(name) VALUES ('Wola Uhruska');
INSERT INTO City(name) VALUES ('Tianguá');
INSERT INTO City(name) VALUES ('Skelleftehamn');
INSERT INTO City(name) VALUES ('Póvoa de Penela');
INSERT INTO City(name) VALUES ('Gelan');
INSERT INTO City(name) VALUES ('Xinhe');
INSERT INTO City(name) VALUES ('Kabac');
INSERT INTO City(name) VALUES ('?a?am');
INSERT INTO City(name) VALUES ('Gopaan');
INSERT INTO City(name) VALUES ('Zayt?');
INSERT INTO City(name) VALUES ('Jiantianjie');
INSERT INTO City(name) VALUES ('Yumbe');
INSERT INTO City(name) VALUES ('Ufimskiy');
INSERT INTO City(name) VALUES ('Palaihari');
INSERT INTO City(name) VALUES ('Mapaniqui');
INSERT INTO City(name) VALUES ('Perechyn');
INSERT INTO City(name) VALUES ('Vogar');
INSERT INTO City(name) VALUES ('Nanyuki');
INSERT INTO City(name) VALUES ('San Antonio');
INSERT INTO City(name) VALUES ('Gusang');
INSERT INTO City(name) VALUES ('Piura');
INSERT INTO City(name) VALUES ('Chicago');
INSERT INTO City(name) VALUES ('São Gonçalo do Sapucaí');
INSERT INTO City(name) VALUES ('Camlachie');
INSERT INTO City(name) VALUES ('Ichihara');
INSERT INTO City(name) VALUES ('Giraldo');
INSERT INTO City(name) VALUES ('Perivóli');
INSERT INTO City(name) VALUES ('Tanggulangin');
INSERT INTO City(name) VALUES ('Trondheim');
INSERT INTO City(name) VALUES ('Brämhult');
INSERT INTO City(name) VALUES ('Cherga');
INSERT INTO City(name) VALUES ('Yanwukou');
INSERT INTO City(name) VALUES ('Dahua');
INSERT INTO City(name) VALUES ('Orzu');
INSERT INTO City(name) VALUES ('Jagna');
INSERT INTO City(name) VALUES ('Itajaí');
INSERT INTO City(name) VALUES ('Huilong');
INSERT INTO City(name) VALUES ('Wang Sam Mo');
INSERT INTO City(name) VALUES ('Kalej');
INSERT INTO City(name) VALUES ('Wenping');
INSERT INTO City(name) VALUES ('Azogues');
INSERT INTO City(name) VALUES ('Kavajë');
INSERT INTO City(name) VALUES ('Tolbazy');
INSERT INTO City(name) VALUES ('Shiniujiang');
INSERT INTO City(name) VALUES ('Tsybulevka');
INSERT INTO City(name) VALUES ('Tulihe');
INSERT INTO City(name) VALUES ('Washington');
INSERT INTO City(name) VALUES ('Montecristi');
INSERT INTO City(name) VALUES ('San Antonio');
INSERT INTO City(name) VALUES ('Ladoang');
INSERT INTO City(name) VALUES ('Chotepe');
INSERT INTO City(name) VALUES ('Port Antonio');
INSERT INTO City(name) VALUES ('Jixing');
INSERT INTO City(name) VALUES ('Combita');
INSERT INTO City(name) VALUES ('Revolucion');
INSERT INTO City(name) VALUES ('Oliveira');
INSERT INTO City(name) VALUES ('Omsukchan');
INSERT INTO City(name) VALUES ('Stockholm');
INSERT INTO City(name) VALUES ('Huangji');
INSERT INTO City(name) VALUES ('Itaúna');
INSERT INTO City(name) VALUES ('Hule');
INSERT INTO City(name) VALUES ('Nipawin');
INSERT INTO City(name) VALUES ('Jaguaribe');
INSERT INTO City(name) VALUES ('Arrabal');
INSERT INTO City(name) VALUES ('Pawonków');
INSERT INTO City(name) VALUES ('Soutinho');
INSERT INTO City(name) VALUES ('Bodzechów');
INSERT INTO City(name) VALUES ('Tougan');
INSERT INTO City(name) VALUES ('Três de Maio');
INSERT INTO City(name) VALUES ('Saint Louis');
INSERT INTO City(name) VALUES ('Budrus');
INSERT INTO City(name) VALUES ('Kontagora');
INSERT INTO City(name) VALUES ('Jiulonggang');
INSERT INTO City(name) VALUES ('San Calixto');
INSERT INTO City(name) VALUES ('Bofuer');
INSERT INTO City(name) VALUES ('Jiuhua');
INSERT INTO City(name) VALUES ('Ho?oby');
INSERT INTO City(name) VALUES ('Jiawu');
INSERT INTO City(name) VALUES ('Cipeundeuy');
INSERT INTO City(name) VALUES ('Staronizhestebliyevskaya');
INSERT INTO City(name) VALUES ('Votorantim');
INSERT INTO City(name) VALUES ('Th? Tr?n Tam S?n');
INSERT INTO City(name) VALUES ('Layog');
INSERT INTO City(name) VALUES ('Sanguanzhai');
INSERT INTO City(name) VALUES ('Mazhonghe');
INSERT INTO City(name) VALUES ('Iroquois Falls');
INSERT INTO City(name) VALUES ('Siparia');
INSERT INTO City(name) VALUES ('Morávka');
INSERT INTO City(name) VALUES ('Changxing');
INSERT INTO City(name) VALUES ('Cap-Santé');
INSERT INTO City(name) VALUES ('Karangbaru');
INSERT INTO City(name) VALUES ('Lexington');
INSERT INTO City(name) VALUES ('Panxi');
INSERT INTO City(name) VALUES ('Alor Setar');
INSERT INTO City(name) VALUES ('Shaoxing');
INSERT INTO City(name) VALUES ('Rosebank');
INSERT INTO City(name) VALUES ('?ar?b');
INSERT INTO City(name) VALUES ('Nkpor');
INSERT INTO City(name) VALUES ('Pojok');
INSERT INTO City(name) VALUES ('Troitsk');
INSERT INTO City(name) VALUES ('Yuncheng');
INSERT INTO City(name) VALUES ('Honghuatao');
INSERT INTO City(name) VALUES ('Mingshan');
INSERT INTO City(name) VALUES ('Tongliao');
INSERT INTO City(name) VALUES ('Lampa');
INSERT INTO City(name) VALUES ('Duru');
INSERT INTO City(name) VALUES ('Slobodka');
INSERT INTO City(name) VALUES ('Shicheng');
INSERT INTO City(name) VALUES ('Barinitas');
INSERT INTO City(name) VALUES ('Atlantis');
INSERT INTO City(name) VALUES ('Fankeng');
INSERT INTO City(name) VALUES ('Sarilhos Grandes');
INSERT INTO City(name) VALUES ('Kiev');
INSERT INTO City(name) VALUES ('Dulangan');
INSERT INTO City(name) VALUES ('Huanghu');
INSERT INTO City(name) VALUES ('Kašina');
INSERT INTO City(name) VALUES ('Mathambgwane');
INSERT INTO City(name) VALUES ('Uruaçu');
INSERT INTO City(name) VALUES ('Sajia');
INSERT INTO City(name) VALUES ('Moulay Bouchta');
INSERT INTO City(name) VALUES ('San Bernardo');
INSERT INTO City(name) VALUES ('Ambovombe');
INSERT INTO City(name) VALUES ('Gravatá');
INSERT INTO City(name) VALUES ('Nybro');
INSERT INTO City(name) VALUES ('Vallenar');
INSERT INTO City(name) VALUES ('Vitarte');
INSERT INTO City(name) VALUES ('Yishui');
INSERT INTO City(name) VALUES ('Zavety Il’icha');
INSERT INTO City(name) VALUES ('Zavoronezhskoye');
INSERT INTO City(name) VALUES ('Nkove');
INSERT INTO City(name) VALUES ('Caraguatatuba');
INSERT INTO City(name) VALUES ('Jaguarari');
INSERT INTO City(name) VALUES ('Shangkuli');
INSERT INTO City(name) VALUES ('Usarin');
INSERT INTO City(name) VALUES ('San Pedro');
INSERT INTO City(name) VALUES ('Xin’an');
INSERT INTO City(name) VALUES ('Al Fukhkh?r?');
INSERT INTO City(name) VALUES ('Amirdzhan');
INSERT INTO City(name) VALUES ('Wum');
INSERT INTO City(name) VALUES ('A? ?aw?lah');
INSERT INTO City(name) VALUES ('Kosmonosy');
INSERT INTO City(name) VALUES ('Suç');
INSERT INTO City(name) VALUES ('Zhamog');
INSERT INTO City(name) VALUES ('Serov');
INSERT INTO City(name) VALUES ('Ust-Maya');
INSERT INTO City(name) VALUES ('Longxi');
INSERT INTO City(name) VALUES ('Chumen');
INSERT INTO City(name) VALUES ('Toledo');
INSERT INTO City(name) VALUES ('Zhuji');
INSERT INTO City(name) VALUES ('Pasto');
INSERT INTO City(name) VALUES ('Hengfeng');
INSERT INTO City(name) VALUES ('Xinshidu');
INSERT INTO City(name) VALUES ('Wonorejo Dua');
INSERT INTO City(name) VALUES ('Morgados');
INSERT INTO City(name) VALUES ('Hendaye');
INSERT INTO City(name) VALUES ('Zumarraga');
INSERT INTO City(name) VALUES ('Olhão');
INSERT INTO City(name) VALUES ('Pionerskiy');
INSERT INTO City(name) VALUES ('Lazaro Cardenas');
INSERT INTO City(name) VALUES ('Kouqian');
INSERT INTO City(name) VALUES ('Alaverdi');
INSERT INTO City(name) VALUES ('Falköping');
INSERT INTO City(name) VALUES ('Aroa');
INSERT INTO City(name) VALUES ('Strum');
INSERT INTO City(name) VALUES ('Utsunomiya-shi');
INSERT INTO City(name) VALUES ('Saint Paul');
INSERT INTO City(name) VALUES ('Spanish Wells');
INSERT INTO City(name) VALUES ('Tr?bki');
INSERT INTO City(name) VALUES ('Plei Kâ?n');
INSERT INTO City(name) VALUES ('Zhiletovo');
INSERT INTO City(name) VALUES ('Lucan');
INSERT INTO City(name) VALUES ('Changleng');
INSERT INTO City(name) VALUES ('Mayskiy');
INSERT INTO City(name) VALUES ('Marovoay');
INSERT INTO City(name) VALUES ('Pueblo Nuevo');
INSERT INTO City(name) VALUES ('Pontalina');
INSERT INTO City(name) VALUES ('Caeté');
INSERT INTO City(name) VALUES ('Fukuyama');
INSERT INTO City(name) VALUES ('?abno');
INSERT INTO City(name) VALUES ('Tarragona');
INSERT INTO City(name) VALUES ('?ubarjal');
INSERT INTO City(name) VALUES ('Dongsheng');
INSERT INTO City(name) VALUES ('??i Ngô');
INSERT INTO City(name) VALUES ('Ostrožac');
INSERT INTO City(name) VALUES ('Tangerang');
INSERT INTO City(name) VALUES ('Haiyang');
INSERT INTO City(name) VALUES ('Chengjiang');
INSERT INTO City(name) VALUES ('Poctol');
INSERT INTO City(name) VALUES ('Xiaoduchuan');
INSERT INTO City(name) VALUES ('Gaocun');
INSERT INTO City(name) VALUES ('Liurenba');
INSERT INTO City(name) VALUES ('Cawalo');
INSERT INTO City(name) VALUES ('Ash Sh?m?yah');
INSERT INTO City(name) VALUES ('Renhe');
INSERT INTO City(name) VALUES ('Kalej');
INSERT INTO City(name) VALUES ('Miramichi');
INSERT INTO City(name) VALUES ('Runovi?');
INSERT INTO City(name) VALUES ('Shuikou');
INSERT INTO City(name) VALUES ('D?rayy?');
INSERT INTO City(name) VALUES ('Beppu');
INSERT INTO City(name) VALUES ('Danville');
INSERT INTO City(name) VALUES ('Sandaogou');
INSERT INTO City(name) VALUES ('Pemzashen');
INSERT INTO City(name) VALUES ('Sokol’niki');
INSERT INTO City(name) VALUES ('Tower');
INSERT INTO City(name) VALUES ('Ayolas');
INSERT INTO City(name) VALUES ('Strömsund');
INSERT INTO City(name) VALUES ('Cancela');
INSERT INTO City(name) VALUES ('Karanggedang');
INSERT INTO City(name) VALUES ('Jinqiao');
INSERT INTO City(name) VALUES ('Cândido Mota');
INSERT INTO City(name) VALUES ('Dob');
INSERT INTO City(name) VALUES ('Gaomiaoji');
INSERT INTO City(name) VALUES ('Qingxi');
INSERT INTO City(name) VALUES ('Zhaoxiang');
INSERT INTO City(name) VALUES ('Ehu');
INSERT INTO City(name) VALUES ('Liutang');
INSERT INTO City(name) VALUES ('Malitubog');
INSERT INTO City(name) VALUES ('Linhares');
INSERT INTO City(name) VALUES ('Novorossiysk');
INSERT INTO City(name) VALUES ('Tutup');
INSERT INTO City(name) VALUES ('Paris La Défense');
INSERT INTO City(name) VALUES ('Niepos');
INSERT INTO City(name) VALUES ('Tungawan');
INSERT INTO City(name) VALUES ('Burunday');
INSERT INTO City(name) VALUES ('Liulin');
INSERT INTO City(name) VALUES ('Zamboanguita');
INSERT INTO City(name) VALUES ('Pregrada');
INSERT INTO City(name) VALUES ('Borås');
INSERT INTO City(name) VALUES ('Rada Tilly');
INSERT INTO City(name) VALUES ('Bang Racham');
INSERT INTO City(name) VALUES ('Pont Cassé');
INSERT INTO City(name) VALUES ('Clarin');
INSERT INTO City(name) VALUES ('Burevestnik');
INSERT INTO City(name) VALUES ('Härnösand');
INSERT INTO City(name) VALUES ('Ferapontovo');
INSERT INTO City(name) VALUES ('Kostrzyn nad Odr?');
INSERT INTO City(name) VALUES ('Billa');
INSERT INTO City(name) VALUES ('San Lorenzo');
INSERT INTO City(name) VALUES ('Kanashevo');
INSERT INTO City(name) VALUES ('Wolanów');
INSERT INTO City(name) VALUES ('Cisitu');
INSERT INTO City(name) VALUES ('Krotoszyn');
INSERT INTO City(name) VALUES ('Lat Lum Kaeo');
INSERT INTO City(name) VALUES ('Hova');
INSERT INTO City(name) VALUES ('Inuyama');
INSERT INTO City(name) VALUES ('Houyu');
INSERT INTO City(name) VALUES ('Cuenca');
INSERT INTO City(name) VALUES ('Og?ri-shimog?');
INSERT INTO City(name) VALUES ('Zabrat');
INSERT INTO City(name) VALUES ('Pujijie');
INSERT INTO City(name) VALUES ('Satrejan');
INSERT INTO City(name) VALUES ('Manalongon');
INSERT INTO City(name) VALUES ('Ban L?ng');
INSERT INTO City(name) VALUES ('Västerås');
INSERT INTO City(name) VALUES ('Itajaí');
INSERT INTO City(name) VALUES ('Huangtang');
INSERT INTO City(name) VALUES ('Cikendi');
INSERT INTO City(name) VALUES ('Klapagading');
INSERT INTO City(name) VALUES ('K?evka');
INSERT INTO City(name) VALUES ('Repušnica');
INSERT INTO City(name) VALUES ('Sindangsari');
INSERT INTO City(name) VALUES ('Murmino');
INSERT INTO City(name) VALUES ('Diónysos');
INSERT INTO City(name) VALUES ('Olopa');
INSERT INTO City(name) VALUES ('Yuping');
INSERT INTO City(name) VALUES ('K? Anh');
INSERT INTO City(name) VALUES ('Nawá');
INSERT INTO City(name) VALUES ('In?ija');
INSERT INTO City(name) VALUES ('S?czów');
INSERT INTO City(name) VALUES ('Laiponda');
INSERT INTO City(name) VALUES ('Zhangyelu');
INSERT INTO City(name) VALUES ('Vynohradivka');
INSERT INTO City(name) VALUES ('Shushicë');
INSERT INTO City(name) VALUES ('Delicias');
INSERT INTO City(name) VALUES ('Kojagete');
INSERT INTO City(name) VALUES ('Motala');
INSERT INTO City(name) VALUES ('Ängelholm');
INSERT INTO City(name) VALUES ('Xuanma');
INSERT INTO City(name) VALUES ('Goim');
INSERT INTO City(name) VALUES ('Roma');
INSERT INTO City(name) VALUES ('Fovissste');
INSERT INTO City(name) VALUES ('Nandong');
INSERT INTO City(name) VALUES ('San Kamphaeng');
INSERT INTO City(name) VALUES ('Xiamazhuang');
INSERT INTO City(name) VALUES ('Mi?etice');
INSERT INTO City(name) VALUES ('Jaleswar');
INSERT INTO City(name) VALUES ('Kadurahayu');
INSERT INTO City(name) VALUES ('Atengmelang');
INSERT INTO City(name) VALUES ('Stockholm');
INSERT INTO City(name) VALUES ('Cemara');
INSERT INTO City(name) VALUES ('Mucumpiz');
INSERT INTO City(name) VALUES ('Longford');
INSERT INTO City(name) VALUES ('Vittel');
INSERT INTO City(name) VALUES ('Raofeng');
INSERT INTO City(name) VALUES ('Abaetetuba');
INSERT INTO City(name) VALUES ('Fanzhuang');
INSERT INTO City(name) VALUES ('Yengiawat');
INSERT INTO City(name) VALUES ('Punta Hermosa');
INSERT INTO City(name) VALUES ('Zgornje Pirni?e');
INSERT INTO City(name) VALUES ('Doumen');
INSERT INTO City(name) VALUES ('Cintawana');
INSERT INTO City(name) VALUES ('D?rchul?');
INSERT INTO City(name) VALUES ('Lagayan');
INSERT INTO City(name) VALUES ('La Sarre');
INSERT INTO City(name) VALUES ('Briceni');
INSERT INTO City(name) VALUES ('Mohelno');
INSERT INTO City(name) VALUES ('Parnamirim');
INSERT INTO City(name) VALUES ('Santa Teresa');
INSERT INTO City(name) VALUES ('Baliton');
INSERT INTO City(name) VALUES ('Pospelikha');
INSERT INTO City(name) VALUES ('Jawhar');
INSERT INTO City(name) VALUES ('Ia Kha');
INSERT INTO City(name) VALUES ('Weekaka');
INSERT INTO City(name) VALUES ('Lanipao');
INSERT INTO City(name) VALUES ('San Vicente');
INSERT INTO City(name) VALUES ('Aoluguya Ewenke Minzu');
INSERT INTO City(name) VALUES ('Palma Soriano');
INSERT INTO City(name) VALUES ('Chejiazhuang');
INSERT INTO City(name) VALUES ('Gunungputri');
INSERT INTO City(name) VALUES ('Ipatinga');
INSERT INTO City(name) VALUES ('Dean');
INSERT INTO City(name) VALUES ('W?d? al ‘Uy?n');
INSERT INTO City(name) VALUES ('Shaxi');
INSERT INTO City(name) VALUES ('Xinyang');
INSERT INTO City(name) VALUES ('Privlaka');
INSERT INTO City(name) VALUES ('La Calera');
INSERT INTO City(name) VALUES ('Perpignan');
INSERT INTO City(name) VALUES ('Ibirataia');
INSERT INTO City(name) VALUES ('Luftinjë');
INSERT INTO City(name) VALUES ('Dongwan');
INSERT INTO City(name) VALUES ('Guagua');
INSERT INTO City(name) VALUES ('Yelizovo');
INSERT INTO City(name) VALUES ('Atlantis');
INSERT INTO City(name) VALUES ('Campo Belo');
INSERT INTO City(name) VALUES ('Nianpan');
INSERT INTO City(name) VALUES ('Gongdao');
INSERT INTO City(name) VALUES ('Santiago');
INSERT INTO City(name) VALUES ('Salento');
INSERT INTO City(name) VALUES ('Niyang');
INSERT INTO City(name) VALUES ('Nanto-shi');
INSERT INTO City(name) VALUES ('Independencia');
INSERT INTO City(name) VALUES ('Dongba');
INSERT INTO City(name) VALUES ('Železniki');
INSERT INTO City(name) VALUES ('Rejoagung');
INSERT INTO City(name) VALUES ('Kasugai');
INSERT INTO City(name) VALUES ('Vorob’yovo');
INSERT INTO City(name) VALUES ('Danxi');
INSERT INTO City(name) VALUES ('Concepción de la Barranca');
INSERT INTO City(name) VALUES ('Guayabal');
INSERT INTO City(name) VALUES ('Kelowna');
INSERT INTO City(name) VALUES ('Lobanovo');
INSERT INTO City(name) VALUES ('Ábrego');
INSERT INTO City(name) VALUES ('Peace River');
INSERT INTO City(name) VALUES ('Razgrad');

