alter session set "_ORACLE_SCRIPT"=true;  

-- USER SQL

CREATE USER "DRUCIAK" IDENTIFIED BY "szbd"  ;

-- QUOTAS

-- ROLES

-- SYSTEM PRIVILEGES
GRANT SELECT ANY TABLE TO "DRUCIAK" ;
GRANT CREATE TABLE TO "DRUCIAK" ;
GRANT DROP ANY TABLE TO "DRUCIAK" ;
GRANT ALTER USER TO "DRUCIAK" ;
GRANT UPDATE ANY TABLE TO "DRUCIAK" ;
GRANT DROP USER TO "DRUCIAK" ;
GRANT INSERT ANY TABLE TO "DRUCIAK" ;
GRANT CREATE ANY TABLE TO "DRUCIAK" ;

ALTER USER DRUCIAK quota unlimited on USERS;

alter session set current_schema = druciak; 