alter session set "_ORACLE_SCRIPT"=true;  

-- USER SQL

CREATE USER "OWNER" IDENTIFIED BY "szbd"  ;

-- QUOTAS

-- ROLES

-- SYSTEM PRIVILEGES
GRANT SELECT ANY TABLE TO "OWNER" ;
GRANT CREATE TABLE TO "OWNER" ;
GRANT DROP ANY TABLE TO "OWNER" ;
GRANT ALTER USER TO "OWNER" ;
GRANT UPDATE ANY TABLE TO "OWNER" ;
GRANT DROP USER TO "OWNER" ;
GRANT INSERT ANY TABLE TO "OWNER" ;
GRANT CREATE ANY TABLE TO "OWNER" ;

ALTER USER OWNER quota unlimited on USERS;

alter session set current_schema = owner; 